import {attachFavorites} from './favorites-picker.js';
import {createBilling} from './billing.js';
import {createMessages} from './messages.js';
import {validateMedia,configureCaptureButtons} from './media-validation.js';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';
import { SUPABASE_URL, SUPABASE_KEY, OAUTH_READY } from './config.js';
import { openStoryEditor } from './story-editor.js';
import { attachCatalog } from './catalog.js';
import { createCommunity } from './community.js';
import { createBetaTools } from './beta-tools.js';
import {createEnhancements} from './enhancements.js';
import {getDraft,saveDraft,deleteDraft,uploadWithProgress} from './drafts.js';
import { storyGroups, rememberStoryGroup, storyGroupOpened } from './story-order.js';
const db=createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let user=null,me=null,view=new URLSearchParams(location.search).has('chat')?'messages':'feed',feed=[],busy=false,toastTimer,loadId=0;
const revealed=new Set();
const postBodies=new Map();
let engagementReady=false;
const billing=createBilling({db,$,modal,esc,toast,getUser:()=>user,auth,refresh:load});
const community=createCommunity({getBilling:()=>billing,getBeta:()=>beta,db,$,esc,result,modal,close,toast,fail,guarded,requireProfile,getUser:()=>user,getMe:()=>me,getEnhancements:()=>enhancements,isEnhanced:()=>engagementReady,showProfile,card,bindCards,signed,avatar,recordView,isRevealed:id=>revealed.has(id),openFeed:(kind,series=null)=>{view=kind;selectedSeries=series;mainCatalog.reset();if(series)$('#series-filter').value=series.label;load();}});
const beta=createBetaTools({db,$,esc,result,modal,close,toast,guarded,fail,requireProfile,getUser:()=>user,moderation:(...args)=>community.moderation(...args),refresh:load});
const enhancements=createEnhancements({db,$,esc,result,modal,close,toast,fail,guarded,requireProfile,getUser:()=>user,getMe:()=>me,readMe,refresh:refreshCurrent,showProfile,openPost:id=>community.openPost(id),people:()=>community.people(),spoiler:p=>community.spoiler(p)});
if(new URLSearchParams(location.search).has('chat'))document.body.classList.add('chat-window');
const messages=createMessages({separateWindow:!new URLSearchParams(location.search).has('chat'),db,$,esc,result,requireProfile,getUser:()=>user,avatar,showProfile,fail,getStories:async authors=>{if(!authors.length)return [];const rows=await result(db.from('posts').select('*,profiles!posts_author_fkey(*)').eq('kind','story').eq('status','approved').in('author',authors).gt('expires_at',new Date().toISOString()).order('created_at',{ascending:true}));storyPosts=[...new Map([...storyPosts,...rows].map(p=>[p.id,p])).values()];return rows;},storySeen:author=>storyGroupOpened(storyPosts,author,storyHistory()),openStory:async id=>{const p=storyPosts.find(p=>p.id===id);storySequence=storyPosts.filter(s=>s.author===p.author&&Date.parse(s.expires_at)>Date.now()).map(s=>s.id);await story(id);}});
const names={messages:'Chat',feed:'Community feed',theory:'Theory room',episodes:'Episode talk',chapters:'Chapter talk',profile:'My profile'};
let storyFollowing=new Set();
let storyPosts=[],activeProfile=null,profilePage=0,profilePosts=[];
const PAGE_SIZE=24;
let selectedSeries=null,feedPage=0,feedHasMore=false;
const catalogMedium=()=>view==='episodes'?'anime':view==='chapters'?'manga':null;
function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').style.display='none',4500);}
function modal(html,storyMode=false){if(!storyMode){stopStoryPlayback();storyEpoch++;storySequence=[];}$('#modal').classList.remove('story-editor-modal','comments-modal','viewers-open');$('#modal').classList.toggle('story-modal',storyMode);$('#modal-body').innerHTML=storyMode?'<div class="story-card">'+html+'</div>':html;$('#modal').scrollTop=0;if(!$('#modal').open)$('#modal').showModal();}
let storyAnimation=0,storyEpoch=0,storySequence=[];
function stopStoryPlayback(){cancelAnimationFrame(storyAnimation);storyAnimation=0;}
function close(){stopStoryPlayback();storyEpoch++;storySequence=[]; $('#modal').close();$('#modal').classList.remove('story-modal','viewers-open'); }
function fail(e){console.error(e);toast(e.message||'Something went wrong. Please try again.');}
async function result(promise){const r=await promise;if(r.error)throw r.error;return r.data;}
function guarded(fn){return async e=>{e?.preventDefault();if(busy)return;busy=true;const buttons=$('#modal-body').querySelectorAll('button');buttons.forEach(b=>b.disabled=true);try{await fn(e);}catch(e){fail(e);}finally{busy=false;buttons.forEach(b=>b.disabled=false);}};}
function requireProfile(){if(me?.account_suspended){toast('Your account is suspended. Contact the moderator from account settings.');return false;}if(!user){auth();return false;}if(!me){profileEditor();return false;}return billing.gate();}
async function readMe(){messages.badge().catch(console.error);if(!engagementReady){const ready=await db.rpc('engagement_ready');engagementReady=!ready.error&&ready.data===true;}me=user?await result(db.from('profiles').select('*').eq('id',user.id).maybeSingle()):null;$('#account').textContent=me?me.display_name:user?'Set up profile':'Sign in';$('.create-row p').textContent=user?'Share a post or add to your story.':'Browse freely. Sign in to join the conversation.';try{await community.refresh();if(engagementReady)await enhancements.loadPins();}catch(e){console.error(e);}}
async function signed(path){if(!path)return null;try{return (await result(db.storage.from('community-media').createSignedUrl(path,60))).signedUrl;}catch{return null;}}
async function avatar(p){const url=await signed(p?.avatar_path);return url?`<img class="avatar" alt="${esc(p.display_name)} profile picture" src="${esc(url)}">`:`<span class="avatar">${esc((p?.display_name||'?')[0].toUpperCase())}</span>`;}
function empty(title,body){return `<div class="empty"><h2>${esc(title)}</h2><p>${esc(body)}</p></div>`;}
const authorStoryCache=new Map();
async function authorStories(author,fresh=false){
 if(!user||!author)return [];
 const key=user.id+':'+author,cached=authorStoryCache.get(key);
 if(!fresh&&cached&&Date.now()-cached.at<30000)return cached.rows.filter(p=>Date.parse(p.expires_at)>Date.now());
 const rows=await result(db.from('posts').select('*,profiles!posts_author_fkey(*)').eq('author',author).eq('kind','story').eq('status','approved').gt('expires_at',new Date().toISOString()).order('created_at',{ascending:true}).order('id').limit(500));
 authorStoryCache.set(key,{at:Date.now(),rows});return rows;
}
async function storyAvatar(profile){
 const picture=await avatar(profile);let rows=[];
 try{rows=await authorStories(profile?.id);}catch{ /* Avatar remains usable if stories cannot be read. */ }
 if(!rows.length)return picture;
 const seen=storyGroupOpened(rows,profile.id,storyHistory());
 return `<button class="author-story-avatar ${seen?'seen-story':''}" data-author-story="${esc(profile.id)}" aria-label="Watch ${esc(profile.display_name)}’s story"><span class="story-ring">${picture}</span></button>`;
}
async function openAuthorStories(author){
 if(!requireProfile())return;
 const rows=await authorStories(author,true);
 if(!rows.length){toast('No active stories to view.');await refreshCurrent();return;}
 storyPosts=[...storyPosts.filter(p=>p.author!==author),...rows];
 storySequence=rows.map(p=>p.id);await story(storySequence[0]);
}
function bindStoryAvatars(root=document){root.querySelectorAll('[data-author-story]').forEach(b=>b.onclick=()=>openAuthorStories(b.dataset.authorStory).catch(fail));}
async function load(){messages.stop();activeProfile=null;const request=++loadId;feedPage=0;feed=[];await billing.status();await billing.returned();if(billing.blocked()&&view!=='profile'){stopStoryPlayback();$('#story-strip').hidden=true;$('.create-row').hidden=true;$('.community-tools').hidden=true;$('#filters').hidden=true;$('#intro').hidden=true;$('#view-title').textContent='FictionCom';$('#content').innerHTML=billing.render();$('#feed-membership').onclick=()=>billing.open().catch(fail);return;}
 $('#story-strip').hidden=['profile','messages'].includes(view);$('.create-row').hidden=['profile','messages'].includes(view);$('.community-tools').hidden=view==='messages';if(!['profile','messages'].includes(view))renderStoryStrip(request);$('#view-title').textContent=names[view];$('#intro').hidden=['profile','feed','messages'].includes(view);$('#filters').hidden=['profile','feed','messages'].includes(view);$('main').classList.toggle('home-feed',view==='feed');document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
 if(selectedSeries&&catalogMedium()&&selectedSeries.medium!==catalogMedium()){selectedSeries=null;mainCatalog.reset();}
 $('#series-page').hidden=!selectedSeries;$('#series-filter').placeholder=view==='episodes'?'Search anime…':view==='chapters'?'Search manga…':'Search anime or manga…';
 $('#content').innerHTML=empty('Loading…','Finding the latest conversations.');
 if(view==='messages'){await messages.inbox();return;}
 if(view==='profile'){if(!user||!me){requireProfile();$('#content').innerHTML=empty('Make yourself at home','Sign in to create your profile.');return;}await showProfile(user.id,request);return;}
 await loadFeedPage(request,true);
}
async function loadFeedPage(request,reset=false){try{
 let q=db.from('posts').select('*,profiles!posts_author_fkey(*)').neq('kind','avatar');
 if(view==='feed')q=user||engagementReady?db.rpc('home_feed',{page_number:feedPage,limit_count:PAGE_SIZE}).select('*,profiles!posts_author_fkey(*)'):q.neq('kind','story').order('created_at',{ascending:false}).order('id').range(feedPage*PAGE_SIZE,(feedPage+1)*PAGE_SIZE-1);
 if(view==='theory')q=q.eq('kind','theory');else if(view==='episodes'||view==='chapters')q=q.eq('kind','reaction').eq('medium',catalogMedium());else q=q.neq('kind','story');
 if(view!=='feed'){if(user&&!selectedSeries&&!$('#series-filter').value.trim()&&$('#discussion-sort').value==='recommended')q=db.rpc('recommended_discussions',{tab:view,page_number:feedPage,limit_count:PAGE_SIZE}).select('*,profiles!posts_author_fkey(*)');const title=$('#series-filter').value.trim();if(selectedSeries)q=q.eq('series',selectedSeries.title).eq('medium',selectedSeries.medium);else if(title)q=q.ilike('series',title.replace(/[\%_]/g,'\$&'));
 const recommended=user&&!selectedSeries&&!title&&$('#discussion-sort').value==='recommended';const sort=$('#discussion-sort').value;if(!recommended){if(sort==='episode-asc'||sort==='episode-desc')q=q.order('episode',{ascending:sort==='episode-asc',nullsFirst:false}).order('created_at',{ascending:false});else q=q.order('created_at',{ascending:sort==='oldest'});q=q.order('id',{ascending:true}).range(feedPage*PAGE_SIZE,(feedPage+1)*PAGE_SIZE-1);}}
 const posts=await result(q);if(view==='feed'&&user){const follows=await result(db.from('follows').select('following').eq('follower',user.id).eq('accepted',true));const circle=new Set([user.id,...follows.map(f=>f.following)]);posts.forEach(p=>p.suggested=!circle.has(p.author));}if(request!==loadId)return;const cards=await Promise.all(posts.map(card));if(request!==loadId)return;
 if(reset)$('#content').innerHTML=`<div id="feed-posts"></div><button id="more-discussions" class="quiet load-more">${view==='feed'?'Load more posts':'Load more discussions'}</button>`;
 feed.push(...posts);feedPage++;feedHasMore=posts.length===PAGE_SIZE;$('#feed-posts').insertAdjacentHTML('beforeend',cards.join(''));if(!feed.length)$('#feed-posts').innerHTML=empty('No discussions yet',selectedSeries?'Be the first to post about '+selectedSeries.label+'.':'Choose a series or start a new conversation.');const more=$('#more-discussions');more.hidden=!feedHasMore;more.disabled=false;more.onclick=()=>{more.disabled=true;loadFeedPage(request);};bindCards();
 }catch(e){if(request!==loadId)return;if(reset)$('#content').innerHTML=empty('Couldn’t load discussions','Please refresh to try again.');else{toast('Couldn’t load more. Please try again.');$('#more-discussions').disabled=false;}console.error(e);}}
async function card(p){postBodies.set(p.id,p.body||'');const author=p.profiles;const stats=await result(db.rpc('post_stats',{target:p.id}));const liked=user?await result(db.from('likes').select('user_id').eq('post_id',p.id).eq('user_id',user.id).maybeSingle()):null;const isHidden=community.spoiler(p)&&!revealed.has(p.id);let media='';if(p.media_path&&!isHidden&&p.kind!=='story'){const url=await signed(p.media_path);if(url)media=p.media_type==='video'?`<video class="media" src="${esc(url)}" controls preload="metadata" data-video="${p.id}"></video>`:`<img class="media" src="${esc(url)}" alt="Image shared by ${esc(author?.display_name)}" loading="lazy">`;}
 if(!isHidden&&p.media_path&&p.kind!=='story'){
 const attachments=await result(db.from('post_media').select('*').eq('post_id',p.id).order('position'));
 for(const a of attachments){const url=await signed(a.path);if(url)media+=a.media_type==='video'?`<video class="media" src="${esc(url)}" controls preload="metadata" data-video="${p.id}"></video>`:`<img class="media" src="${esc(url)}" alt="Additional post image" loading="lazy">`;}
 if(attachments.length)media=`<div class="media-carousel" aria-label="Post attachments">${media}</div><p class="small carousel-hint">Swipe to see all ${attachments.length+1} attachments</p>`;
 }
 const label=p.series?`${p.series}${p.kind==='reaction'&&p.episode?` · ${p.medium==='manga'?'Chapter':'Episode'} ${p.episode}`:''}`:'Community';
 return `<article class="post ${view==='feed'?'social-post':''}" data-post="${p.id}"><div class="post-head">${await storyAvatar(author)}<button data-person="${p.author}"><strong>${esc(author?.display_name)}</strong><div class="meta">@${esc(author?.username)} · ${new Date(p.created_at).toLocaleDateString()}</div></button><div class="post-summary"><span class="tag">${esc(p.kind==='post'?'POST':p.kind.toUpperCase())}</span><span class="small">${stats.views||0} ${stats.views===1?'view':'views'}</span>${p.suggested?'<span class="small">Suggested for you</span>':''}</div></div>${view==='feed'&&!isHidden?media:''}<div class="post-body"><button class="text-button" data-series="${esc(p.series)}" data-medium="${p.medium}">${esc(label)}</button>${p.status!=='approved'?`<p class="status">${p.status==='pending'?'Upload incomplete · only visible to you':'Upload removed · only visible to you'}</p>`:''}</div>${isHidden?`<div class="spoiler"><strong>Spoilers ahead</strong><p>${esc(label)}</p><button data-reveal="${p.id}">Reveal post</button></div>`:`<div class="post-body">${p.title?`<h2>${esc(p.title)}</h2>`:''}<p class="post-copy" data-copy="${p.id}">${esc(p.body.length>320?p.body.slice(0,320).trimEnd()+'…':p.body)}</p>${p.body.length>320?`<button class="text-button" data-expand="${p.id}" aria-expanded="false">Show more</button>`:''}</div>${view==='feed'?'':media}${p.kind==='story'?`<div class="post-body"><button data-story="${p.id}" class="primary">Watch story</button><p class="small">Expires ${new Date(p.expires_at).toLocaleString()}</p></div>`:''}`}<div class="actions"><button data-like="${p.id}" class="${liked?'liked':''}" aria-label="${liked?'Unlike':'Like'} post">♡ ${stats.likes||0}</button><button data-comments="${p.id}">Comments ${stats.comments||0}</button><button data-save="${p.id}">Save</button>${engagementReady&&p.suggested?`<button data-dismiss="${p.id}">Not interested</button>`:''}${engagementReady&&p.author===user?.id&&p.status==='approved'&&!['story','avatar'].includes(p.kind)?`<button data-pin="${p.id}">${enhancements.isPinned(p.id)?'Unpin':'Pin'}</button>`:''}${p.author===user?.id&&p.media_path&&p.status==='pending'?`<button data-ai-review="${p.id}">Finish upload</button>`:''}${p.author===user?.id?`${!['story','avatar'].includes(p.kind)&&p.status==='approved'?`<button data-edit-post="${p.id}">Edit</button>`:''}<button data-delete="${p.id}">Delete</button>${p.kind==='story'?`<button data-viewers="${p.id}">Viewers</button>`:''}`:`<button data-report="${p.id}">Report</button>`}</div></article>`;
}
function bindCards(){bindStoryAvatars();document.querySelectorAll('[data-pin]').forEach(b=>b.onclick=()=>enhancements.pin(b.dataset.pin).catch(fail));document.querySelectorAll('[data-dismiss]').forEach(b=>b.onclick=()=>enhancements.dismiss(b.dataset.dismiss).catch(fail));document.querySelectorAll('[data-expand]').forEach(b=>b.onclick=()=>{const expanded=b.getAttribute('aria-expanded')==='true',body=postBodies.get(b.dataset.expand)||'';b.closest('article').querySelector('[data-copy]').textContent=expanded?body.slice(0,320).trimEnd()+'…':body;b.setAttribute('aria-expanded',String(!expanded));b.textContent=expanded?'Show more':'Show less';});document.querySelectorAll('[data-edit-post]').forEach(b=>b.onclick=()=>editPost(b.dataset.editPost).catch(fail));document.querySelectorAll('[data-ai-review]').forEach(b=>b.onclick=async()=>{b.disabled=true;try{await reviewUpload(b.dataset.aiReview);await refreshCurrent();}catch(e){fail(e);}finally{b.disabled=false;}});document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>community.save(b.dataset.save).catch(fail));document.querySelectorAll('[data-series]').forEach(b=>b.onclick=()=>{if(b.dataset.series)community.hub({title:b.dataset.series,medium:b.dataset.medium}).catch(fail);});document.querySelectorAll('.post-head').forEach(h=>{const person=h.querySelector('[data-person]'),av=h.querySelector('.avatar');if(person&&av&&!av.closest('[data-author-story]')){av.style.cursor='pointer';av.onclick=()=>showProfile(person.dataset.person);}});document.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>showProfile(b.dataset.person));document.querySelectorAll('[data-like]').forEach(b=>b.onclick=async()=>{if(!requireProfile())return;b.disabled=true;try{const id=b.dataset.like;const liked=await result(db.from('likes').select('*').eq('post_id',id).eq('user_id',user.id).maybeSingle());await result(liked?db.from('likes').delete().eq('post_id',id).eq('user_id',user.id):db.from('likes').insert({post_id:id,user_id:user.id}));const stats=await result(db.rpc('post_stats',{target:id}));document.querySelectorAll('[data-like]').forEach(button=>{if(button.dataset.like!==id)return;button.classList.toggle('liked',!liked);button.setAttribute('aria-label',(!liked?'Unlike':'Like')+' post');button.textContent='♡ '+(stats.likes||0);});}catch(e){fail(e);}finally{b.disabled=false;}});
 document.querySelectorAll('[data-reveal]').forEach(b=>b.onclick=()=>{revealed.add(b.dataset.reveal);if($('#modal').open)community.openPost(b.dataset.reveal).catch(fail);else refreshCurrent();});document.querySelectorAll('[data-comments]').forEach(b=>b.onclick=()=>community.conversation(b.dataset.comments).catch(fail));document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>deletePost(b.dataset.delete));document.querySelectorAll('[data-report]').forEach(b=>b.onclick=()=>report(b.dataset.report));document.querySelectorAll('[data-viewers]').forEach(b=>b.onclick=()=>viewers(b.dataset.viewers).catch(fail));document.querySelectorAll('[data-story]').forEach(b=>b.onclick=()=>story(b.dataset.story).catch(fail));document.querySelectorAll('[data-video]').forEach(v=>v.onplay=()=>recordView(v.dataset.video));if(me){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){const p=feed.find(p=>p.id===e.target.dataset.post);if(p&&p.media_type!=='video'&&(!community.spoiler(p)||revealed.has(p.id))){recordView(p.id);observer.unobserve(e.target);}}}),{threshold:0.5});document.querySelectorAll('article[data-post]').forEach(a=>observer.observe(a));}}
async function recordView(id){if(!me)return;const r=await db.from('post_views').insert({post_id:id,user_id:user.id});if(r.error&&r.error.code!=='23505')console.error(r.error);}
const storyHistoryCache=new Map();
function storyHistory(){const key=user?.id||'guest';if(storyHistoryCache.has(key))return storyHistoryCache.get(key);try{const value=JSON.parse(localStorage.getItem('animecom-story-opened:'+key)||'{}');const history=value&&typeof value==='object'&&!Array.isArray(value)?value:{};storyHistoryCache.set(key,history);return history;}catch{return {};}}
async function paintStoryStrip(request=loadId){
 const strip=$('#story-strip');const signature=JSON.stringify([user?.id,me?.avatar_path,me?.display_name,storyPosts.map(p=>[p.id,p.author,p.profiles?.avatar_path,p.profiles?.display_name]),[...storyFollowing],storyHistory()]);if(strip.dataset.paintSignature===signature&&strip.children.length)return;if(!user){if(request!==loadId)return;strip.hidden=view==='profile';strip.dataset.paintSignature=signature;strip.innerHTML='<div class="own-story-bubble"><button class="story-bubble add-story" id="your-story" aria-label="Sign in to add your story"><span class="story-ring"><span class="avatar">◎</span></span><span>Your story</span></button><button class="story-plus" id="add-story" aria-label="Sign in to add a story">+</button></div>';$('#your-story').onclick=createStory;$('#add-story').onclick=createStory;return;}const history=storyHistory(),groups=storyGroups(storyPosts.filter(p=>p.author===user.id||storyFollowing.has(p.author)),user.id,history,storyFollowing),own=storyPosts.find(p=>p.author===user?.id),ownSeen=own&&storyGroupOpened(storyPosts,user.id,history);
 const ownHtml=`<div class="own-story-bubble"><button class="story-bubble ${own?(ownSeen?'seen-story':''):'add-story'}" id="your-story" ${own?`data-story="${own.id}"`:''} aria-label="${own?'Watch your story':'Add your story'}"><span class="story-ring">${me?await avatar(me):'<span class="avatar">◎</span>'}</span><span>Your story</span></button><button class="story-plus" id="add-story" aria-label="Add another story">+</button></div>`;
 const bubbles=await Promise.all(groups.map(async g=>`<button class="story-bubble ${g.opened?'seen-story':''}" data-story="${g.post.id}" aria-label="Watch ${esc(g.post.profiles.display_name)}’s story"><span class="story-ring">${await avatar(g.post.profiles)}</span><span>${esc(g.post.profiles.display_name)}</span></button>`));
 if(request!==loadId)return;strip.dataset.paintSignature=signature;strip.innerHTML=ownHtml+bubbles.join('');
 $('#add-story').onclick=createStory;if(!own)$('#your-story').onclick=createStory;
 strip.querySelectorAll('[data-story]').forEach(b=>b.onclick=()=>story(b.dataset.story).catch(fail));
}
function markStoryOpened(p){document.querySelectorAll('[data-author-story]').forEach(b=>{if(b.dataset.authorStory===p.author)b.classList.add('seen-story');});const history=rememberStoryGroup(storyPosts,p.author,storyHistory());storyHistoryCache.set(user?.id||'guest',history);try{localStorage.setItem('animecom-story-opened:'+(user?.id||'guest'),JSON.stringify(history));}catch{}paintStoryStrip().catch(console.error);}
async function renderStoryStrip(request=loadId){
 const owner=user?.id;if(!owner){storyPosts=[];storyFollowing=new Set();await paintStoryStrip(request);return;}
 try{const following=new Set((await result(db.from('follows').select('following').eq('follower',owner).eq('accepted',true))).map(f=>f.following));const posts=await result(db.from('posts').select('*,profiles!posts_author_fkey(*)').eq('kind','story').gt('expires_at',new Date().toISOString()).in('author',[owner,...following]).order('created_at',{ascending:false}).limit(500));if(request!==loadId||user?.id!==owner)return;storyFollowing=following;storyPosts=posts.sort((a,b)=>Date.parse(a.created_at)-Date.parse(b.created_at));await paintStoryStrip(request);}
 catch{if(request!==loadId||user?.id!==owner)return;if(!$('#story-strip').children.length)await paintStoryStrip(request);}
}
async function refreshCurrent(){if(activeProfile)await showProfile(activeProfile);else await load();}
function createStory(){if(!requireProfile())return;openStoryEditor({modal,onPublish:async(file,metadata)=>{await uploadPost(file,{...metadata,author:user.id});close();toast('Your story is live.');view='feed';await load();}});}
function storyIcon(type){const paths={mute:'<path d="M11 5 6 9H3v6h3l5 4V5Z"/><path d="m16 9 5 6m0-6-5 6"/>',sound:'<path d="M11 5 6 9H3v6h3l5 4V5Z"/><path d="M15 8a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/>',pause:'<path d="M8 5v14m8-14v14"/>',play:'<path d="m8 5 11 7-11 7V5Z"/>'};return `<svg viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[type]}</svg>`;}
async function story(id){
 const epoch=++storyEpoch;stopStoryPlayback();
 if(!storySequence.length){const authors=[user?.id,...storyGroups(storyPosts,user?.id,storyHistory(),storyFollowing).map(g=>g.post.author)].filter(Boolean);storySequence=authors.flatMap(a=>storyPosts.filter(p=>p.author===a).map(p=>p.id));}
 const p=storyPosts.find(p=>p.id===id);if(!p)return;
 const siblings=storyPosts.filter(x=>x.author===p.author),index=siblings.findIndex(x=>x.id===id),own=p.author===user?.id;
 const sequenceIndex=storySequence.indexOf(id);
 const header=`<div class="story-owner"><button class="story-owner-profile" data-story-profile="${p.author}" aria-label="View ${esc(p.profiles.display_name)}’s profile">${await avatar(p.profiles)}</button><div><strong>${esc(p.profiles.display_name)}</strong><span class="meta">${Math.max(1,Math.floor((Date.now()-Date.parse(p.created_at))/3600000))}h</span></div></div>`;
 if(epoch!==storyEpoch)return;
 if(community.spoiler(p)&&!revealed.has(id)){markStoryOpened(p);modal(header+`<div class="spoiler"><h2>Spoilers ahead</h2><p>${esc(p.series)} · ${p.medium==='manga'?'Chapter':'Episode'} ${p.episode||'?'}</p><button id="reveal-story">Watch story</button></div>`,true);$('#reveal-story').onclick=()=>{revealed.add(id);story(id).catch(fail);};return;}
 const url=await signed(p.media_path);if(epoch!==storyEpoch)return;if(!url)throw Error('This story is unavailable.');
 modal(`<div class="story-progress">${siblings.map((_,i)=>`<span class="${i<=index?'watched':''}"></span>`).join('')}</div>`+header+`<div id="story-stage" class="story-stage">${p.media_type==='video'?`<video autoplay muted playsinline src="${esc(url)}"></video>`:`<img src="${esc(url)}" alt="${esc(p.body||'Story photo')}">`}<button id="prev-story" class="story-nav story-nav-prev" aria-label="Previous story" ${sequenceIndex===0?'disabled':''}>‹</button><button id="next-story" class="story-nav story-nav-next" aria-label="Next story" ${sequenceIndex===storySequence.length-1?'disabled':''}>›</button>${'<button id="story-menu-toggle" class="story-menu-toggle" aria-label="Story options" aria-expanded="false">⋯</button><div id="story-menu" class="story-menu" hidden><button id="story-menu-action" class="danger">'+(own?'Delete story':'Report story')+'</button></div>'}</div><p class="story-caption">${esc(p.body)}</p>${own&&p.status!=='approved'?`<p class="status">${p.status==='pending'?'Upload incomplete · only visible to you':'Story removed · only visible to you'}</p>${p.status==='pending'?'<button id="retry-story-review">Finish upload</button>':''}`:''}<div class="story-top-controls"><button id="mute-story" aria-label="Unmute story">${storyIcon('mute')}</button><button id="pause-story" aria-label="Pause story">${storyIcon('pause')}</button></div>${own?'<button id="story-viewers" class="viewer-trigger" aria-expanded="false"><span class="viewer-chevron" aria-hidden="true">⌃</span><span>Viewers</span></button><section id="story-viewer-panel" class="story-viewer-sheet" hidden></section>':''}`,true);
 $('.story-card').insertAdjacentHTML('beforeend',`<section id="story-interactions" class="${own?'own-story-interactions':''}"></section>`);await enhancements.storyControls(p);
 $('#modal-body').querySelector('[data-story-profile]').onclick=()=>{close();showProfile(p.author);};const cardNode=$('.story-card');cardNode.append($('#prev-story'),$('#next-story'));const neighborIds=[storySequence[sequenceIndex-1],storySequence[sequenceIndex+1]];await Promise.all(neighborIds.map(async(neighborId,i)=>{const neighbor=storyPosts.find(s=>s.id===neighborId);if(!neighbor)return;const safe=!community.spoiler(neighbor)||revealed.has(neighbor.id),previewUrl=safe?await signed(neighbor.media_path):null;if(epoch!==storyEpoch||!cardNode.isConnected)return;const preview=document.createElement('button');preview.className='story-neighbor '+(i?'story-neighbor-next':'story-neighbor-prev');preview.setAttribute('aria-label',(i?'Next':'Previous')+' story by '+neighbor.profiles.display_name);preview.innerHTML=(previewUrl?(neighbor.media_type==='video'?`<video src="${esc(previewUrl)}" muted playsinline preload="metadata"></video>`:`<img src="${esc(previewUrl)}" alt="">`):'<span>Spoiler hidden</span>')+`<strong>${esc(neighbor.profiles.display_name)}</strong>`;preview.onclick=()=>story(neighborId).catch(fail);$('#modal-body').append(preview);}));if(epoch!==storyEpoch)return;
 markStoryOpened(p);
 if($('#retry-story-review'))$('#retry-story-review').onclick=guarded(async()=>{await reviewUpload(id);await renderStoryStrip();await story(id);});
 const next=()=>{if(sequenceIndex+1<storySequence.length)story(storySequence[sequenceIndex+1]).catch(fail);else close();};const previous=()=>{if(sequenceIndex>0)story(storySequence[sequenceIndex-1]).catch(fail);};
 $('#prev-story').onclick=previous;$('#next-story').onclick=next;
 {$('#story-menu-toggle').onclick=()=>{const menu=$('#story-menu');menu.hidden=!menu.hidden;$('#story-menu-toggle').setAttribute('aria-expanded',String(!menu.hidden));if(!menu.hidden)$('#story-stage video')?.pause();else if($('#pause-story').dataset.paused!=='true')$('#story-stage video')?.play().catch(()=>{});};}$('#story-menu-action').onclick=()=>{stopStoryPlayback();if(own)deletePost(id);else report(id);};
 const stage=$('#story-stage'),video=stage.querySelector('video');$('#mute-story').disabled=!video;$('#mute-story').onclick=()=>{if(!video)return;video.muted=!video.muted;$('#mute-story').innerHTML=storyIcon(video.muted?'mute':'sound');$('#mute-story').setAttribute('aria-label',video.muted?'Unmute story':'Mute story');};let paused=false,elapsed=0,last=performance.now();const pause=()=>{paused=!paused;$('#pause-story').dataset.paused=String(paused);$('#pause-story').innerHTML=storyIcon(paused?'play':'pause');$('#pause-story').setAttribute('aria-label',paused?'Resume story':'Pause story');if(video){if(paused)video.pause();else video.play().catch(()=>{});}};$('#pause-story').onclick=pause;let lastSwipe=0;stage.onclick=e=>{if(e.target.closest('button')||Date.now()-lastSwipe<400)return;$('#pause-story').click();};stage.tabIndex=0;stage.setAttribute('aria-label','Story media. Tap or press space to pause or resume.');stage.onkeydown=e=>{if(e.target!==stage)return;if(e.key===' '){e.preventDefault();$('#pause-story').click();}if(e.key==='ArrowRight')next();if(e.key==='ArrowLeft')previous();};
 if(video)video.onended=next;
 const tick=now=>{if(epoch!==storyEpoch||!$('#modal').open)return;const panelOpen=$('#story-viewer-panel')&&!$('#story-viewer-panel').hidden;if(!paused&&!document.hidden&&!panelOpen&&(!$('#story-menu')||$('#story-menu').hidden)&&!video&&!document.activeElement?.closest('#story-reply-form'))elapsed+=Math.min(now-last,200);last=now;const fraction=video?(video.duration?video.currentTime/video.duration:0):Math.min(elapsed/5000,1);const bar=$('.story-progress').children[index];bar.style.background=`linear-gradient(to right,var(--accent) ${fraction*100}%,#424961 ${fraction*100}%)`;if(!video&&elapsed>=5000){next();return;}storyAnimation=requestAnimationFrame(tick);};storyAnimation=requestAnimationFrame(tick);
 let swipeStart=null;stage.addEventListener('touchstart',e=>{swipeStart={x:e.touches[0].clientX,y:e.touches[0].clientY};},{passive:true});stage.addEventListener('touchend',e=>{if(!swipeStart)return;const dx=e.changedTouches[0].clientX-swipeStart.x,dy=e.changedTouches[0].clientY-swipeStart.y;if(Math.abs(dx)>70||Math.abs(dy)>60)lastSwipe=Date.now();if(Math.abs(dx)>70&&Math.abs(dy)<60){if(dx<0)next();else previous();}swipeStart=null;},{passive:true});
 if(own){let start=null;const stage=$('#story-stage');stage.addEventListener('touchstart',e=>{const t=e.touches[0];start={x:t.clientX,y:t.clientY};},{passive:true});stage.addEventListener('touchend',e=>{const t=e.changedTouches[0];if(start&&start.y-t.clientY>60&&Math.abs(start.x-t.clientX)<80)viewers(id,true).catch(fail);start=null;},{passive:true});$('#story-viewers').onclick=()=>{if(!$('#story-viewer-panel').hidden)collapseStoryViewers();else viewers(id,true).catch(fail);};}
 await recordView(id);
}
function collapseStoryViewers(){const panel=$('#story-viewer-panel');if(!panel)return;panel.hidden=true;$('#modal').classList.remove('viewers-open');const trigger=$('#story-viewers');trigger.setAttribute('aria-expanded','false');trigger.innerHTML='<span class="viewer-chevron" aria-hidden="true">⌃</span><span>Viewers</span>';if($('#pause-story')?.dataset.paused!=='true'&&(!$('#story-menu')||$('#story-menu').hidden))$('#story-stage video')?.play().catch(()=>{});}
async function viewers(id,inline=false){
 const p=storyPosts.find(p=>p.id===id);if(!user||!p||p.author!==user.id)throw Error('Only the story owner can see its viewer list.');
 $('#story-stage video')?.pause();
 const rows=await result(db.from('post_views').select('user_id,profiles!post_views_user_id_fkey(*)').eq('post_id',id));
 if(rows.length){const active=await result(db.from('posts').select('*,profiles!posts_author_fkey(*)').eq('kind','story').in('author',rows.map(r=>r.user_id)).gt('expires_at',new Date().toISOString()).order('created_at',{ascending:true}).limit(500));storyPosts=[...new Map([...storyPosts,...active].map(p=>[p.id,p])).values()];}
 const storyLikes=await result(db.from('likes').select('user_id').eq('post_id',id)),likedViewers=new Set(storyLikes.map(l=>l.user_id));
 const history=storyHistory();
 const people=await Promise.all(rows.map(async r=>{
  const person=r.profiles,active=storyPosts.find(s=>s.author===r.user_id),seen=active&&storyGroupOpened(storyPosts,r.user_id,history);
  const picture=await avatar(person);
  return `<li class="story-viewer-row">${active?`<button class="viewer-story ${seen?'seen-story':''}" data-viewer-story="${active.id}" aria-label="Watch ${esc(person?.display_name)}’s story"><span class="story-ring">${picture}</span></button>`:picture}<button class="viewer-profile" data-viewer-profile="${r.user_id}"><strong>${esc(person?.display_name)}</strong><span class="meta">@${esc(person?.username)}</span></button>${likedViewers.has(r.user_id)?'<span class="viewer-liked" aria-label="Liked your story">♥</span>':''}</li>`;
 }));
 const html=`<h2>${rows.length} ${rows.length===1?'viewer':'viewers'}</h2><p class="small">Unique signed-in viewers. Only you can see this list.</p><ul class="viewer-list">${people.join('')||'<li class="small">No views yet.</li>'}</ul>`;
 if(inline&&$('#story-viewer-panel')){$('#story-viewer-panel').innerHTML=html;$('#story-viewer-panel').hidden=false;$('#story-viewers').setAttribute('aria-expanded','true');$('#story-viewers').innerHTML='<span class="viewer-chevron" aria-hidden="true">⌄</span><span>Viewers</span>';$('#modal').classList.add('viewers-open');}else modal(html);

 $('#modal-body').querySelectorAll('[data-viewer-story]').forEach(b=>b.onclick=()=>story(b.dataset.viewerStory).catch(fail));
 $('#modal-body').querySelectorAll('[data-viewer-profile]').forEach(b=>b.onclick=()=>{close();showProfile(b.dataset.viewerProfile).catch(fail);});
}
function auth(mode='signin'){
 const signup=mode==='signup';modal(`<h2>${signup?'Create your FictionCom account':'Welcome back'}</h2><p class="small">${signup?'7 days free with a card, then $5 USD/month automatically unless cancelled. Set up your profile, then add your card securely through Stripe. Read the <a href="terms.html" target="_blank" rel="noopener">Terms</a> and <a href="privacy.html" target="_blank" rel="noopener">Privacy notice</a> first.':'Sign in to post, react, and follow your favorite creators.'}</p><form id="auth-form"><label>Email<input id="email" type="email" autocomplete="email" required></label><label>Password<input id="password" type="password" ${signup?'minlength="10"':''} autocomplete="${signup?'new-password':'current-password'}" required></label>${signup?'<label>Confirm password<input id="confirm-password" type="password" autocomplete="new-password" required></label><label class="check"><input id="accept-rules" type="checkbox" required> I am at least 14 years old and agree to the community rules, Terms and Privacy notice. No nudity, explicit content, harassment, or stolen work.</label>':''}<p id="auth-error" class="error" role="alert"></p><button class="primary auth-submit">${signup?'Create account':'Sign in'}</button><p class="small">${signup?'Already have an account?':'New to FictionCom?'} <button id="auth-switch" type="button" class="text-button">${signup?'Sign in':'Create account'}</button></p>${signup?'':'<button type="button" id="reset" class="quiet">Forgot password?</button>'}</form>`);
 const oauth=provider=>guarded(async()=>{await result(db.auth.signInWithOAuth({provider,options:{redirectTo:location.origin+location.pathname}}));});if($('#google')){$('#google').onclick=oauth('google');$('#google').disabled=!OAUTH_READY.google;if(!OAUTH_READY.google)$('#google').textContent='Google sign-in · coming soon';}$('#auth-switch').onclick=()=>auth(signup?'signin':'signup');
 $('#auth-form').onsubmit=guarded(async()=>{const email=$('#email').value.trim().toLowerCase(),password=$('#password').value;$('#auth-error').textContent='';try{if(signup){if(password!==$('#confirm-password').value)throw Error('Your passwords do not match.');const data=await result(db.auth.signUp({email,password,options:{emailRedirectTo:location.origin+location.pathname,data:{age_14_or_older:true}}}));if(Array.isArray(data.user?.identities)&&data.user.identities.length===0)throw Error('This email is already linked to an account. Sign in instead, or use Forgot password to recover access.');if(data.session){close();toast('Account registered. Add your card to start your free trial.');}else{modal('<h2>Start your 7-day free trial</h2><p><strong>7 days free, then $5 USD/month.</strong></p><p>Your registration request is received. Verify your email using the confirmation link, then sign in to add your card securely through Stripe.</p><p>Your trial starts after card setup. No charge today. After seven days, your card is charged $5/month unless you cancel. Cancel anytime.</p><button id="back-signin" class="primary">Sign in to add your card</button>');$('#back-signin').onclick=()=>auth();}}else{await result(db.auth.signInWithPassword({email,password}));close();toast('Welcome back.');}}catch(e){$('#auth-error').textContent=signup&&(['user_already_exists','email_exists'].includes(e.code)||/already (?:registered|exists)/i.test(e.message||''))?'This email is already linked to an account. Sign in instead, or use Forgot password to recover access.':e.message||'Unable to sign in. Please try again.';}});
 if(!signup)$('#reset').onclick=()=>requestPasswordReset($('#email').value.trim());
}
function requestPasswordReset(initialEmail=''){
 modal(`<h2>Reset your password</h2><p>Confirm the email address linked to your account. We'll send a secure link to reset your password.</p><form id="reset-request"><label>Email address<input id="reset-email" type="email" autocomplete="email" value="${esc(initialEmail)}" required></label><label>Confirm email address<input id="reset-email-confirm" type="email" autocomplete="email" required></label><p id="reset-error" class="error" role="alert"></p><button class="primary">Send reset link</button><button id="reset-back" type="button" class="quiet">Back to sign in</button></form>`);
 $('#reset-back').onclick=()=>auth();
 $('#reset-request').onsubmit=guarded(async()=>{const email=$('#reset-email').value.trim().toLowerCase(),confirmation=$('#reset-email-confirm').value.trim().toLowerCase();$('#reset-error').textContent='';if(email!==confirmation){$('#reset-error').textContent='The email addresses do not match.';return;}try{await result(db.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname}));modal('<h2>Check your email</h2><p>If an account exists for this email address, we’ll send a password reset link. Check your inbox and spam folder.</p><button id="reset-done" class="primary">Back to sign in</button>');$('#reset-done').onclick=()=>auth();}catch(e){$('#reset-error').textContent=e.message||'Unable to request a reset link. Please try again.';}});
}
function passwordReset(){modal('<h2>Choose a new password</h2><form id="new-password"><label>New password<input id="new-pass" type="password" minlength="10" autocomplete="new-password" required></label><button class="primary">Save password</button></form>');$('#new-password').onsubmit=guarded(async()=>{await result(db.auth.updateUser({password:$('#new-pass').value}));modal('<h2>Password reset successfully</h2><p>Your password has been updated. You can now sign in with your new password.</p><button id="password-reset-signin" class="primary">Back to sign in</button>');$('#password-reset-signin').onclick=guarded(async()=>{await result(db.auth.signOut());auth();});});}
async function registrationNext(){const membership=await billing.status();if(!membership.moderator&&!membership.trial_started_at)await billing.open();else profileEditor();}
function profileEditor(){if(!user){auth();return;}const introducing=!me;modal(`<h2>${me?'Edit your profile':'Make your introduction'}</h2><form id="profile-form"><label>Username<input id="username" value="${esc(me?.username)}" pattern="[a-z0-9_]{3,24}" minlength="3" maxlength="24" required placeholder="e.g. moonlit_manga"></label><label>Display name<input id="display-name" value="${esc(me?.display_name)}" maxlength="60" required></label><label>Bio<textarea id="bio" maxlength="500">${esc(me?.bio)}</textarea></label><label>Favorite anime & manga<input id="favorites" value="${esc(me?.favorites)}" maxlength="300" placeholder="The series you love"></label><label class="check"><input id="private" type="checkbox" ${me?.is_private?'checked':''}> Private account · approve followers</label>${!me?'<label class="check"><input type="checkbox" required> I am at least 14 and agree to the Terms, Privacy notice and community rules.</label>':''}<label>New profile picture<input id="profile-file" type="file" accept="image/jpeg,image/png,image/webp"></label><p class="small">Photos and anime avatars are welcome. No nudity or inappropriate pictures. Maximum 10 MB.</p><label class="check"><input id="profile-ai-consent" type="checkbox"> If I upload a picture, I confirm it follows the no-nudity and community rules.</label><button class="primary">Save profile</button></form>`);const favoritesPicker=attachFavorites($('#favorites'),me?.favorite_series||[]);$('#profile-form').onsubmit=guarded(async()=>{const fields={username:$('#username').value.trim().toLowerCase(),display_name:$('#display-name').value.trim(),bio:$('#bio').value,favorites:favoritesPicker.value(),favorite_series:favoritesPicker.series(),is_private:$('#private').checked};try{if(me)await result(db.from('profiles').update(fields).eq('id',user.id));else await result(db.from('profiles').insert({id:user.id,...fields}));}catch(e){if(e.code==='23505')throw Error('That username is already taken. Choose another username.');throw e;}const file=$('#profile-file').files[0];if(file&&!$('#profile-ai-consent').checked)throw Error('Confirm the community rules before uploading a profile picture.');if(file)await uploadPost(file,{author:user.id,kind:'avatar',title:'Profile picture',body:'',series:'',medium:'anime',spoiler:false});await readMe();close();toast(file?'Profile saved. Picture uploaded.':'Profile saved.');view='profile';await load();if(introducing)await billing.open();});}
async function showProfile(id,request){try{
 activeProfile=id;$('#story-strip').hidden=true;$('.create-row').hidden=true;profilePage=0;profilePosts=[];const profileRequest=request||++loadId;
 const p=await result(db.from('profiles').select('*').eq('id',id).single());
 const rows=await result(db.from('follows').select('*').or(`follower.eq.${id},following.eq.${id}`));
 const counts=await result(db.rpc('profile_counts',{target:id}));
 const relation=rows.find(f=>f.follower===user?.id&&f.following===id),own=id===user?.id;
 const countResponse=await db.from('posts').select('id',{count:'exact',head:true}).eq('author',id).neq('kind','avatar').neq('kind','story');if(countResponse.error)throw countResponse.error;
 const avatars=own?await result(db.from('posts').select('*').eq('author',id).eq('kind','avatar').order('created_at',{ascending:false}).limit(5)):[];
 if(profileRequest!==loadId)return;
 $('#view-title').textContent=own?'My profile':p.display_name;$('#filters').hidden=true;$('#intro').hidden=true;
 $('#content').innerHTML=`<section class="profile-top"><div class="profile-header"><div class="profile-avatar">${await storyAvatar(p)}</div><div class="profile-identity"><h2>${esc(p.display_name)}</h2><div class="meta">@${esc(p.username)}${p.is_private?' · Private account':''}</div><div class="profile-stats"><span><strong>${countResponse.count||0}</strong> posts</span><button id="profile-followers"><strong>${counts.followers||0}</strong> followers</button><button id="profile-following"><strong>${counts.following||0}</strong> following</button></div></div></div><p>${esc(p.bio)}</p><p class="small">${esc(p.favorites)}</p><div class="form-actions">${own?'<button id="edit-profile">Edit profile</button><button id="account-settings">Saved & settings</button><button id="signout">Sign out</button>':`<button id="follow" class="primary">${relation?(relation.accepted?'Unfollow':'Cancel request'):(p.is_private?'Request to follow':'Follow')}</button><button id="block">Block account</button>`}</div></section>${own&&avatars.length?`<section class="rail-card"><h2>Profile pictures</h2>${avatars.map(a=>`<div class="person"><span>${esc(a.status)} · ${new Date(a.created_at).toLocaleDateString()}</span>${a.status==='pending'?`<button data-avatar-review="${a.id}">Finish upload</button>`:''}${a.status==='approved'?`<button data-use-avatar="${esc(a.media_path)}">Use picture</button>`:''}</div>`).join('')}</section>`:''}${own?'<div id="requests"></div>':''}${engagementReady?`<div id="profile-shelves" data-owner="${id}"></div>`:''}<div class="profile-grid-label"><span aria-hidden="true">▦</span> Posts</div><div id="profile-grid" class="profile-grid"></div><button id="more-posts" class="quiet load-more">Load more posts</button>`;
 if(engagementReady)await enhancements.profile(id);await loadProfilePage(id,profileRequest);
 bindStoryAvatars($('#content'));$('#profile-followers').onclick=()=>community.people(id,'Followers').catch(fail);$('#profile-following').onclick=()=>community.people(id,'Following').catch(fail);
 if(own){$('#account-settings').onclick=()=>community.settings().catch(fail);$('#edit-profile').onclick=profileEditor;$('#signout').onclick=()=>{modal('<h2>Sign out?</h2><p>Are you sure you want to log out?</p><div class="form-actions"><button id="cancel-signout" type="button">No</button><button id="confirm-signout" type="button" class="primary">Yes</button></div>');$('#cancel-signout').onclick=close;$('#confirm-signout').onclick=guarded(async()=>{const button=$('#confirm-signout');button.disabled=true;try{await result(db.auth.signOut());close();}catch(error){if(button.isConnected)button.disabled=false;throw error;}});$('#cancel-signout').focus();};document.querySelectorAll('[data-use-avatar]').forEach(b=>b.onclick=async()=>{try{await result(db.from('profiles').update({avatar_path:b.dataset.useAvatar}).eq('id',user.id));await readMe();await load();}catch(e){fail(e);}});document.querySelectorAll('[data-avatar-review]').forEach(b=>b.onclick=guarded(async()=>{await reviewUpload(b.dataset.avatarReview);await load();}));await requests(rows.filter(f=>f.following===id&&!f.accepted));}
 else{$('#follow').onclick=async()=>{if(!requireProfile())return;try{await result(relation?db.from('follows').delete().eq('follower',user.id).eq('following',id):db.from('follows').insert({follower:user.id,following:id}));await showProfile(id);}catch(e){fail(e);}};$('#block').onclick=()=>{if(!requireProfile())return;modal(`<h2>Block @${esc(p.username)}?</h2><p>You will no longer see each other’s posts while signed in.</p><button id="confirm-block" class="primary">Block account</button>`);$('#confirm-block').onclick=guarded(async()=>{await result(db.from('blocks').insert({blocker:user.id,blocked:id}));close();view='feed';await load();});};}
 }catch(e){fail(e);}}
async function loadProfilePage(id,request){const button=$('#more-posts');button.disabled=true;try{
 const posts=await result(engagementReady?db.rpc('profile_feed',{target:id,page_number:profilePage}).select('*,profiles!posts_author_fkey(*)'):db.from('posts').select('*,profiles!posts_author_fkey(*)').eq('author',id).neq('kind','avatar').neq('kind','story').order('created_at',{ascending:false}).range(profilePage*PAGE_SIZE,(profilePage+1)*PAGE_SIZE-1));
 const tiles=await Promise.all(posts.map(async p=>{const stats=await result(db.rpc('post_stats',{target:p.id}));const url=!community.spoiler(p)?await signed(p.media_path):null;return `<div class="profile-tile">${engagementReady&&enhancements.isPinned(p.id,p.author)?'<span class="pinned-label">Pinned</span>':''}<button data-open-post="${p.id}" class="profile-thumbnail" aria-label="Open ${esc(p.title||p.series||'post')}">${community.spoiler(p)?'<span class="tile-text">Spoilers<br>Tap to reveal</span>':url?(p.media_type==='video'?`<video muted preload="metadata" src="${esc(url)}"></video><span class="tile-kind">▶</span>`:`<img loading="lazy" src="${esc(url)}" alt="${esc(p.title||p.series||'Post photo')}">`):`<span class="tile-text">${esc(p.title||p.body.slice(0,90))}</span>`}${p.status!=='approved'?`<span class="tile-status">${esc(p.status)}</span>`:''}</button><div class="tile-stats"><span>◉ ${stats.views||0} views</span><span>♡ ${stats.likes||0}</span></div></div>`;}));
 if(request!==loadId||activeProfile!==id)return;profilePosts.push(...posts);profilePage++;$('#profile-grid').insertAdjacentHTML('beforeend',tiles.join(''));
 if(!profilePosts.length)$('#profile-grid').innerHTML=empty('No visible posts','Public posts appear here. Private posts require an approved follow request.');button.hidden=posts.length<PAGE_SIZE;button.onclick=()=>loadProfilePage(id,request).catch(fail);
 document.querySelectorAll('[data-open-post]').forEach(b=>b.onclick=()=>openProfilePost(b.dataset.openPost).catch(fail));
 }finally{button.disabled=false;}}
async function openProfilePost(id){const p=profilePosts.find(p=>p.id===id);if(!p)return;feed=profilePosts;modal(await card(p));bindCards();const reveal=$('#modal-body [data-reveal]');if(reveal)reveal.onclick=()=>{revealed.add(id);openProfilePost(id).catch(fail);};if(!community.spoiler(p)||revealed.has(id))await recordView(id);}

async function requests(rows){if(!rows.length)return;const people=await result(db.from('profiles').select('*').in('id',rows.map(r=>r.follower)));$('#requests').innerHTML=`<section class="rail-card"><h2>Follow requests</h2><div class="people">${people.map(p=>`<div class="person"><span>@${esc(p.username)}</span><button data-accept="${p.id}">Accept</button><button data-decline="${p.id}">Decline</button></div>`).join('')}</div></section>`;document.querySelectorAll('[data-accept]').forEach(b=>b.onclick=async()=>{try{await result(db.from('follows').update({accepted:true}).eq('follower',b.dataset.accept).eq('following',user.id));await load();}catch(e){fail(e);}});document.querySelectorAll('[data-decline]').forEach(b=>b.onclick=async()=>{try{await result(db.from('follows').delete().eq('follower',b.dataset.decline).eq('following',user.id));await load();}catch(e){fail(e);}});}
async function compose(defaultKind){
 if(defaultKind==='story'){createStory();return;}if(!requireProfile())return;
 const context=view,kind=context==='theory'?'theory':['episodes','chapters'].includes(context)?'reaction':'post',medium=context==='chapters'?'manga':'anime',reaction=kind==='reaction';
 modal(`<h2>${kind==='theory'?'Create a theory':reaction?'Share '+(medium==='anime'?'an episode':'a chapter')+' reaction':'Create a post'}</h2><form id="post-form"><label>Post type<input value="${kind==='theory'?'Theory':reaction?(medium==='anime'?'Episode reaction':'Chapter reaction'):'Post'}" readonly></label><label>Title<input id="title" maxlength="120"></label><label>Your post<textarea id="body" maxlength="5000" required placeholder="Share your thoughts…"></textarea></label><a id="large-editor" class="text-button" target="_blank">Open writing editor in a new tab</a><label>${reaction?(medium==='anime'?'Anime':'Manga'):'Anime or manga'}<input id="series" maxlength="100" placeholder="Choose a series" ${kind!=='post'?'required':''}></label>${reaction?`<label>${medium==='anime'?'Episode':'Chapter'}<input id="episode" type="number" min="1" max="100000" required></label>`:''}<label class="check"><input id="spoiler" type="checkbox"> Contains spoilers</label><div class="media-picker"><span>Photos or short videos</span><input id="media" type="file" multiple accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" hidden><input id="post-camera-photo" type="file" accept="image/*" capture="environment" hidden><input id="post-camera-video" type="file" accept="video/*" capture="environment" hidden><button id="add-post-media" type="button" class="media-picker-button"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="4"/><circle cx="8" cy="8" r="1.5"/><path d="m3 17 6-6 4 4 3-3 5 5"/></svg><span>Add photos or videos</span><span class="media-picker-plus" aria-hidden="true">＋</span></button></div><div class="capture-actions"><button type="button" id="take-post-photo">Take photo</button><button type="button" id="take-post-video">Record video</button></div><div id="attachment-order" class="attachment-order"></div><p id="draft-status" class="small" role="status">Drafts save on this device.</p><button type="button" id="discard-draft" class="text-button">Discard draft</button><div id="upload-status" hidden><progress id="upload-progress" max="100" value="0"></progress><span id="upload-label" role="status"></span></div><p class="small">Up to 6 attachments, 10 MB each. Videos up to 5 minutes. Camera capture is available on supported devices. No nudity or inappropriate content.</p><label class="check"><input type="checkbox" required> My content follows the community rules.</label><button class="primary">Post</button></form>`);
 const form=$('#post-form'),field=id=>form.querySelector('#'+id),owner=user.id,draftKey=owner+':'+context;let postSeries=null,files=[],published=false,timer,writeQueue=Promise.resolve(),previewUrls=[];
 configureCaptureButtons(field('take-post-photo'),field('take-post-video'),field('post-camera-photo'),field('post-camera-video'));
 field('take-post-photo').onclick=()=>field('post-camera-photo').click();field('take-post-video').onclick=()=>field('post-camera-video').click();
 field('add-post-media').onclick=()=>field('media').click();
 const status=message=>{if(form.isConnected)field('draft-status').textContent=message;};
 const snapshot=()=>({title:field('title').value,body:field('body').value,series:field('series').value,selected:postSeries,episode:field('episode')?.value||'',spoiler:field('spoiler').checked,files:files.map(f=>({name:f.name,lastModified:f.lastModified,blob:f}))});
 const persist=()=>{if(published)return writeQueue;const data=snapshot();writeQueue=writeQueue.catch(()=>{}).then(()=>saveDraft(draftKey,data)).then(()=>status('Draft saved on this device.'),()=>status('Device storage is unavailable. Keep this window open to retain your draft.'));return writeQueue;};
 const schedule=()=>{clearTimeout(timer);timer=setTimeout(persist,250);};
 const picker=attachCatalog(field('series'),{getMedium:()=>reaction?medium:null,onSelect:item=>{postSeries=item;schedule();},onClear:()=>{postSeries=null;schedule();}});
 function attachments(){previewUrls.forEach(URL.revokeObjectURL);previewUrls=[];field('attachment-order').innerHTML=files.map((f,i)=>{const url=URL.createObjectURL(f);previewUrls.push(url);return `<div class="attachment-item">${f.type.startsWith('image/')?`<img src="${esc(url)}" alt="Attachment ${i+1}">`:'<span>Video</span>'}<span>${i+1}. ${esc(f.name)}</span><button type="button" data-move-attachment="${i}" data-direction="-1" ${i===0?'disabled':''} aria-label="Move attachment ${i+1} earlier">↑</button><button type="button" data-move-attachment="${i}" data-direction="1" ${i===files.length-1?'disabled':''} aria-label="Move attachment ${i+1} later">↓</button><button type="button" data-remove-attachment="${i}" aria-label="Remove attachment ${i+1}">×</button></div>`;}).join('');field('attachment-order').querySelectorAll('[data-move-attachment]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.moveAttachment),j=i+Number(b.dataset.direction);[files[i],files[j]]=[files[j],files[i]];attachments();schedule();});field('attachment-order').querySelectorAll('[data-remove-attachment]').forEach(b=>b.onclick=()=>{files.splice(Number(b.dataset.removeAttachment),1);attachments();schedule();});}
 async function addMedia(input){const chosen=[...input.files];input.value='';if(files.length+chosen.length>6){toast('Choose up to six attachments.');return;}try{for(const file of chosen)await validateMedia(file,300);if(!form.isConnected)return;files.push(...chosen);attachments();schedule();}catch(e){toast(e.message);}}
 for(const id of ['media','post-camera-photo','post-camera-video'])field(id).onchange=()=>addMedia(field(id));form.addEventListener('input',schedule);
 try{const saved=await getDraft(draftKey);if(saved&&form.isConnected){field('title').value=saved.title||'';field('body').value=saved.body||'';field('series').value=saved.series||'';postSeries=saved.selected||null;if(postSeries)picker.setSelection(postSeries);if(field('episode'))field('episode').value=saved.episode||'';field('spoiler').checked=!!saved.spoiler;files=(saved.files||[]).map(f=>new File([f.blob],f.name,{type:f.blob.type,lastModified:f.lastModified}));attachments();status('Restored your saved draft, including attachments.');}}catch{status('Device storage is unavailable. Keep this window open to retain your draft.');}
 field('discard-draft').onclick=async()=>{clearTimeout(timer);await writeQueue;await deleteDraft(draftKey).catch(()=>{});form.reset();postSeries=null;picker.reset();files=[];attachments();status('Draft discarded.');};
 if(!form.isConnected||!$('#modal').open)return;
 const draftId=crypto.randomUUID(),channel=new BroadcastChannel('animecom-draft-'+draftId);channel.onmessage=e=>{if(!form.isConnected)return;if(e.data?.type==='body'&&typeof e.data.body==='string'){field('body').value=e.data.body.slice(0,5000);schedule();}if(e.data?.type==='ready')channel.postMessage({type:'body',body:field('body').value});};field('body').oninput=()=>channel.postMessage({type:'body',body:field('body').value});field('large-editor').href='write.html#'+draftId;
 $('#modal').addEventListener('close',()=>{clearTimeout(timer);if(!published)persist();previewUrls.forEach(URL.revokeObjectURL);channel.postMessage({type:'closed'});channel.close();},{once:true});
 form.onsubmit=guarded(async()=>{if(kind!=='post'&&!postSeries)throw Error('Choose a series from the suggestions.');await persist();const post={author:owner,kind,title:field('title').value,body:field('body').value,series:postSeries?.title||field('series').value.trim(),medium:postSeries?.medium||medium,episode:reaction?Number(field('episode').value):null,spoiler:field('spoiler').checked};if(files.length){field('upload-status').hidden=false;try{await uploadMediaPost(files,post,fraction=>{if(form.isConnected){field('upload-progress').value=Math.round(fraction*100);field('upload-label').textContent=Math.round(fraction*100)+'% uploaded';}});}catch(e){field('upload-label').textContent='Upload failed. Your draft is retained; press Post to retry.';throw e;}}else await result(db.from('posts').insert(post));published=true;clearTimeout(timer);await writeQueue;await deleteDraft(draftKey).catch(()=>{});channel.postMessage({type:'published'});close();toast('Your post is live.');view=context;await load();});
}
async function uploadPost(file,post){if(post.kind==='story')authorStoryCache.clear();await validateMedia(file,post.kind==='story'?60:300);const allowed=['image/jpeg','image/png','image/webp','video/mp4','video/webm'];if(!allowed.includes(file.type))throw Error('Choose a JPG, PNG, WebP, MP4, or WebM file.');if(file.size>10485760)throw Error('Keep uploads under 10 MB for this beta.');const ext={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','video/mp4':'mp4','video/webm':'webm'}[file.type];const path=`${user.id}/${crypto.randomUUID()}.${ext}`;await uploadWithProgress({db,url:SUPABASE_URL,key:SUPABASE_KEY,path,file,onProgress:fraction=>toast('Uploading '+Math.round(fraction*100)+'%…')});let uploaded;try{uploaded=await result(db.from('posts').insert({...post,ai_review_consent:false,media_path:path,media_type:file.type.startsWith('image/')?'image':'video'}).select('id').single());await result(db.rpc('publish_upload',{target:uploaded.id}));}catch(e){if(uploaded)await db.from('posts').delete().eq('id',uploaded.id).eq('author',user.id);await db.storage.from('community-media').remove([path]);throw e;}}
function report(id){if(!requireProfile())return;modal('<h2>Report this post</h2><form id="report-form"><label>What’s wrong?<select id="reason"><option>Nudity or explicit content</option><option>Harassment or hate</option><option>Missing spoiler warning</option><option>Stolen content</option><option>Spam</option></select></label><button class="primary">Send report</button></form>');$('#report-form').onsubmit=guarded(async()=>{await result(db.from('reports').insert({reporter:user.id,post_id:id,reason:$('#reason').value}));close();toast('Report submitted for review.');});}
async function editPost(id){if(!requireProfile())return;const p=await result(db.from('posts').select('*').eq('id',id).eq('author',user.id).single());modal(`<h2>Edit post</h2><form id="edit-post-form"><label>Title<input id="edit-title" maxlength="120" value="${esc(p.title)}"></label><label>Post<textarea id="edit-body" maxlength="5000" required>${esc(p.body)}</textarea></label>${p.kind==='reaction'?`<label>${p.medium==='anime'?'Episode':'Chapter'}<input id="edit-episode" type="number" min="1" max="100000" value="${p.episode||''}" required></label>`:''}<label class="check"><input id="edit-spoiler" type="checkbox" ${p.spoiler?'checked':''}> Contains spoilers</label><button class="primary">Save changes</button></form>`);$('#edit-post-form').onsubmit=guarded(async()=>{await result(db.rpc('edit_post',{target:id,new_title:$('#edit-title').value,new_body:$('#edit-body').value,new_spoiler:$('#edit-spoiler').checked,new_episode:Number($('#edit-episode')?.value)||null}));close();toast('Post updated.');await refreshCurrent();});}
function deletePost(id){modal('<h2>Delete this post?</h2><p>The post, comments, and likes will be removed.</p><button id="confirm-delete" class="primary">Delete post</button>');$('#confirm-delete').onclick=guarded(async()=>{const p=await result(db.from('posts').select('*').eq('id',id).eq('author',user.id).single());const attachments=await result(db.from('post_media').select('path').eq('post_id',id));await result(db.from('posts').delete().eq('id',id).eq('author',user.id));if(p.kind==='story')authorStoryCache.clear();if(p?.media_path)await db.storage.from('community-media').remove([p.media_path,...attachments.map(a=>a.path)]);close();toast('Post deleted.');await load();});}
function rules(){modal('<h2>A community worth coming back to.</h2><ul class="rules-list"><li>No exposed nipples or genitals, full nudity, explicit sexual activity, or sexual content involving minors or characters depicted as minors. This applies to real photos, anime art, avatars, videos, and stories.</li><li>Exaggerated proportions, cleavage, swimwear, and revealing outfits are allowed when intimate areas are covered and content is not sexually explicit.</li><li>No harassment, hate, threats, impersonation, or spam.</li><li>Share work you own or have permission to post. Credit artists.</li><li>Mark spoilers. Episode and chapter reactions should use the correct number.</li><li>Uploads publish immediately. The moderator reviews reports and can remove rule-breaking posts.</li></ul>');}
const mainCatalog=attachCatalog($('#series-filter'),{getMedium:catalogMedium,onSelect:item=>{selectedSeries=item;load();},onClear:()=>{selectedSeries=null;$('#series-page').hidden=true;}});
$('#series-page').onclick=()=>{if(selectedSeries)community.hub(selectedSeries).catch(fail);};$('#discussion-sort').onchange=()=>load();$('#clear-series').onclick=()=>{selectedSeries=null;mainCatalog.reset();load();};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{mainCatalog.close();if(b.dataset.view!==view){selectedSeries=null;mainCatalog.reset();}view=b.dataset.view;load();});$('#account').onclick=()=>{if(user){view='profile';load();}else auth();};$('#compose').onclick=()=>compose();$('#discover').onclick=()=> (engagementReady?enhancements.discover():community.people()).catch(fail);$('#notifications').onclick=()=>community.notifications().catch(fail);$('#my-series').onclick=()=>community.library().catch(fail);$('#rules').onclick=rules;$('#public-support').onclick=()=>beta.support().catch(fail);$('#public-feedback').onclick=()=>beta.feedback().catch(fail);$('#refresh').onclick=load;$('#filters').onsubmit=e=>{e.preventDefault();load();};$('#close-modal').onclick=close;
db.auth.onAuthStateChange((event,session)=>{const previousId=user?.id;user=session?.user??null;if(event==='INITIAL_SESSION'||event==='TOKEN_REFRESHED'||(event==='SIGNED_IN'&&previousId===user?.id))return;if(event==='USER_UPDATED'){setTimeout(()=>readMe().catch(fail),0);return;}setTimeout(async()=>{try{await readMe();if(event==='PASSWORD_RECOVERY'){passwordReset();return;}if(event==='SIGNED_IN')view='profile';await load();if(event==='SIGNED_IN'&&!me)await registrationNext();}catch(e){fail(e);}},0);});
try{const data=await result(db.auth.getSession());user=data.session?.user??null;if(user&&!new URLSearchParams(location.search).has('chat'))view='profile';await readMe();await load();if(user&&!me)await registrationNext();}catch(e){fail(e);}

async function uploadMediaPost(files,post,onProgress=()=>{}){
 for(const file of files)await validateMedia(file,300);
 if(['story','avatar'].includes(post.kind)&&files.length>1)throw Error('Stories and profile pictures use one attachment.');if(files.length>6)throw Error('Choose up to 6 attachments.');
 const types={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','video/mp4':'mp4','video/webm':'webm'};
 for(const f of files)if(!types[f.type]||f.size>10485760)throw Error('Each attachment must be JPG, PNG, WebP, MP4, or WebM and under 10 MB.');
 const paths=[],attempted=[];let inserted=null,uploadedBytes=0;const totalBytes=files.reduce((n,f)=>n+f.size,0)||1;
 try{for(let i=0;i<files.length;i++){const f=files[i],path=user.id+'/'+crypto.randomUUID()+'.'+types[f.type];toast('Uploading attachment '+(i+1)+' of '+files.length+'…');attempted.push(path);await uploadWithProgress({db,url:SUPABASE_URL,key:SUPABASE_KEY,path,file:f,onProgress:fraction=>onProgress((uploadedBytes+fraction*f.size)/totalBytes)});uploadedBytes+=f.size;paths.push({path,media_type:f.type.startsWith('image/')?'image':'video'});}
 inserted=await result(db.from('posts').insert({...post,ai_review_consent:false,media_path:paths[0].path,media_type:paths[0].media_type}).select('id').single());
 if(paths.length>1)await result(db.from('post_media').insert(paths.slice(1).map((p,i)=>({...p,post_id:inserted.id,position:i+1}))));await result(db.rpc('publish_upload',{target:inserted.id}));
 }catch(e){if(inserted)await db.from('posts').delete().eq('id',inserted.id).eq('author',user.id);if(attempted.length)await db.storage.from('community-media').remove(attempted);throw e;}
}


setInterval(()=>{if(!document.hidden){if(user){community.badge().catch(console.error);readMe().catch(console.error);}if(!activeProfile&&!['messages','profile'].includes(view)&&!$('#modal').open)renderStoryStrip().catch(console.error);}},60000);
$('#modal').addEventListener('close',()=>{stopStoryPlayback();storyEpoch++;storySequence=[];});

async function reviewUpload(id){await result(db.rpc('publish_upload',{target:id}));toast('Upload published.');}
