import {deleteUserDrafts} from './drafts.js';
export function createBetaTools({db,$,esc,result,modal,close,toast,guarded,fail,requireProfile,getUser,moderation,refresh}){
 const uid=()=>getUser()?.id;
 async function stopBilling(owner){
  const {data,error}=await db.auth.getSession();if(error||!data.session)throw Error('Sign in again.');
  const response=await fetch('/api/billing/delete-account',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+data.session.access_token},body:JSON.stringify({user_id:owner})});
  const reply=await response.json();if(!response.ok)throw Error(reply.error||'Could not cancel billing. Please retry before deleting your account.');
 }
 async function removeFiles(owner){let page=0,paths=[];while(true){const rows=await result(db.storage.from('community-media').list(owner,{limit:100,offset:page*100,sortBy:{column:'name',order:'asc'}}));paths.push(...rows.filter(r=>r.id).map(r=>owner+'/'+r.name));if(rows.length<100)break;page++;}for(let i=0;i<paths.length;i+=100)await result(db.storage.from('community-media').remove(paths.slice(i,i+100)));}
 async function deleteAccount(){if(!uid()){requireProfile();return;}if(await result(db.rpc('is_moderator')))throw Error('Transfer moderation before deleting your moderator account.');
 modal('<h2>Delete your account?</h2><p>Are you sure you want to permanently delete your account? Your profile, posts, stories, comments and uploads will be removed. This cannot be undone.</p><form id="delete-account-form"><label>Why are you leaving? (optional)<select id="deletion-reason"><option value="">Prefer not to say</option><option>Not using the app</option><option>Technical problems</option><option>Privacy concerns</option><option>Unwanted content or behavior</option><option>Other</option></select></label><label>Tell us more (optional)<textarea id="deletion-details" maxlength="1000" placeholder="What could we improve?"></textarea></label><p class="small">Feedback is kept separately without an account identifier and is visible only to the moderator. Please do not include personal information.</p><div class="form-actions"><button type="button" id="cancel-delete-account">No</button><button type="submit" id="confirm-delete-account" class="danger">Yes, delete my account</button></div></form>');
 $('#cancel-delete-account').onclick=close;$('#cancel-delete-account').focus();let feedbackSaved=false;
 $('#delete-account-form').onsubmit=guarded(async()=>{const owner=uid(),button=$('#confirm-delete-account');if(!owner)return;button.disabled=true;$('#cancel-delete-account').disabled=true;try{
 const reason=$('#deletion-reason').value,details=$('#deletion-details').value.trim();if(!feedbackSaved&&(reason||details)){await result(db.rpc('save_deletion_feedback',{reason_text:reason||'Other',details_text:details}));feedbackSaved=true;}
 await result(db.rpc('begin_my_deletion'));await stopBilling(owner);toast('Removing uploaded files…');await removeFiles(owner);
 await result(db.rpc('delete_my_account'));await deleteUserDrafts(owner).catch(()=>{});await db.auth.signOut();close();toast('Your account has been deleted.');await refresh();
 }catch(error){if(button.isConnected){button.disabled=false;$('#cancel-delete-account').disabled=false;}throw error;}
 });
 }
 async function feedback(){if(!requireProfile())return;modal(`<h2>Help shape FictionCom</h2><p class="small">Tell us what you’d like to see in the app. Your feedback is shared privately with the moderator.</p><form id="feedback-form"><label>Feedback type<select id="feedback-kind"><option>Feature request</option><option>Improvement</option><option>Bug report</option><option>Other</option></select></label><label>Short title<input id="feedback-title" maxlength="100" required placeholder="What would make FictionCom better?"></label><label>Your idea<textarea id="feedback-body" minlength="3" maxlength="1800" required placeholder="Describe what you want and how it would help you."></textarea></label><button class="primary">Submit feedback</button></form>`);$('#feedback-form').onsubmit=guarded(async()=>{const title=$('#feedback-title').value.trim(),body=$('#feedback-body').value.trim();if(!title||body.length<3)throw Error('Add a title and at least three characters describing your idea.');await result(db.from('support_requests').insert({user_id:uid(),body:'[Feedback · '+$('#feedback-kind').value+'] '+title+'\n\n'+body}));close();toast('Thank you! Your feedback has been submitted.');});}
 async function support(){if(!uid()){modal('<h2>Contact support</h2><p>Email <a href="mailto:doudousygueye1997@gmail.com">doudousygueye1997@gmail.com</a> for account help or questions.</p><button id="support-signin">Sign in for in-app Support</button>');$('#support-signin').onclick=()=>requireProfile();return;}const rows=await result(db.from('support_requests').select('*').eq('user_id',uid()).order('created_at',{ascending:false}).limit(20));
 modal(`<h2>Contact the moderator</h2><p>Send a private question, appeal, or account request to the moderator.</p><form id="support-form"><label>Your message<textarea id="support-message" minlength="3" maxlength="2000" required></textarea></label><button class="primary">Send message</button></form><h3>Your recent messages</h3>${rows.map(r=>`<article class="rail-card"><p>${esc(r.body)}</p><p class="small">${r.reply?'Moderator: '+esc(r.reply):'Awaiting reply'}</p></article>`).join('')||'<p class="small">No messages yet.</p>'}`);
 $('#support-form').onsubmit=guarded(async()=>{await result(db.from('support_requests').insert({user_id:uid(),body:$('#support-message').value.trim()}));toast('Message sent.');await support();});
 }
 async function moderatorCenter(){if(!await result(db.rpc('is_moderator')))throw Error('Moderator access required.');
 modal('<h2>Moderator dashboard</h2><p class="small">Only moderators can access private reports, support messages and review history. AI review is off.</p><div class="form-actions"><button id="review-reports">Review reports</button><button id="moderator-support">Support inbox</button><button id="moderator-log">Review history</button><button id="deletion-feedback">Deletion feedback</button></div><h3>Account enforcement</h3><form id="account-search"><label>Username<input id="moderator-username" minlength="3" maxlength="24" required></label><button>Find account</button></form><div id="enforcement-result"></div><h3>Deletion requests</h3><div id="deletion-queue"></div>');
 $('#deletion-feedback').onclick=guarded(async()=>{const rows=await result(db.from('deletion_feedback').select('reason,details,created_at').order('created_at',{ascending:false}).limit(100));modal('<h2>Deletion feedback</h2>'+ (rows.map(r=>`<article class="rail-card"><strong>${esc(r.reason)}</strong><p>${esc(r.details)}</p><p class="small">${new Date(r.created_at).toLocaleDateString()}</p></article>`).join('')||'<p>No feedback yet.</p>'));});
 $('#review-reports').onclick=()=>moderation('reports').catch(fail);$('#moderator-support').onclick=()=>supportInbox().catch(fail);$('#moderator-log').onclick=()=>history().catch(fail);
 const reportCount=await db.from('reports').select('id',{count:'exact',head:true}).is('resolved_at',null);if(!reportCount.error)$('#review-reports').textContent='Review reports ('+(reportCount.count||0)+')';const supportCount=await db.from('support_requests').select('id',{count:'exact',head:true}).is('reply',null);if(!supportCount.error)$('#moderator-support').textContent='Support inbox ('+(supportCount.count||0)+')';
 const requests=await result(db.from('account_requests').select('*,profiles!account_requests_user_id_fkey(username)').in('status',['pending','processing']).order('created_at').limit(50));$('#deletion-queue').innerHTML=requests.map(r=>`<div class="person"><span>@${esc(r.profiles?.username)} · ${esc(r.status)}</span><button data-process-deletion="${r.id}">Process deletion</button></div>`).join('')||'<p class="small">No pending requests.</p>';
 document.querySelectorAll('[data-process-deletion]').forEach(b=>b.onclick=()=>{modal('<h2>Process requested deletion?</h2><p>This account requested permanent deletion. Uploaded files are removed before the account. A failed operation can be retried; processing requests cannot be cancelled.</p><form id="process-deletion-form"><label>Type DELETE<input id="process-confirm" pattern="DELETE" required></label><button class="danger">Delete requested account</button></form>');$('#process-deletion-form').onsubmit=guarded(async()=>{if($('#process-confirm').value!=='DELETE')return;const target=await result(db.rpc('begin_requested_deletion',{request_id:b.dataset.processDeletion}));await stopBilling(target);await removeFiles(target);await result(db.rpc('finish_requested_deletion',{request_id:b.dataset.processDeletion}));toast('Requested account deleted.');await moderatorCenter();});});
 $('#account-search').onsubmit=guarded(async()=>{const p=await result(db.from('profiles').select('*').eq('username',$('#moderator-username').value.trim().toLowerCase()).maybeSingle());if(!p){$('#enforcement-result').textContent='Account not found.';return;}
  $('#enforcement-result').innerHTML=`<p>@${esc(p.username)} · ${p.account_suspended?'Suspended':'Active'}</p><label>Reason<textarea id="enforcement-reason" maxlength="1000"></textarea></label><button id="enforce-account">${p.account_suspended?'Restore account':'Suspend account'}</button>`;
  $('#enforce-account').onclick=guarded(async()=>{const note=$('#enforcement-reason').value.trim();if(note.length<3)throw Error('Provide a reason.');await result(db.rpc('moderate_account',{target:p.id,suspend:!p.account_suspended,note}));toast('Account decision saved.');await moderatorCenter();});
 });
 }
 async function history(page=0){const rows=await result(db.from('moderation_log').select('*').order('created_at',{ascending:false}).range(page*25,page*25+24));modal(`<h2>Review history</h2>${rows.map(r=>`<article class="rail-card"><strong>${esc(r.action)}</strong><p>${esc(r.reason)}</p><p class="small">${new Date(r.created_at).toLocaleString()}</p></article>`).join('')||'<p>No decisions yet.</p>'}<div class="form-actions"><button id="history-back" ${page?'':'disabled'}>Previous</button><button id="history-next" ${rows.length===25?'':'hidden'}>Next</button><button id="history-home">Dashboard</button></div>`);$('#history-back').onclick=()=>history(page-1).catch(fail);$('#history-next').onclick=()=>history(page+1).catch(fail);$('#history-home').onclick=()=>moderatorCenter().catch(fail);}
 async function supportInbox(page=0){const rows=await result(db.from('support_requests').select('*,profiles!support_requests_user_id_fkey(username)').order('created_at',{ascending:false}).range(page*20,page*20+19));modal(`<h2>Support inbox</h2>${rows.map(r=>`<article class="rail-card"><strong>@${esc(r.profiles?.username)}</strong><p>${esc(r.body)}</p><form data-support-reply="${r.id}"><label>Moderator reply<textarea maxlength="2000" minlength="3" required>${esc(r.reply||'')}</textarea></label><button>Save reply</button></form></article>`).join('')||'<p>No messages.</p>'}<div class="form-actions"><button id="support-prev" ${page?'':'disabled'}>Previous</button><button id="support-next" ${rows.length===20?'':'hidden'}>Next</button><button id="support-home">Dashboard</button></div>`);document.querySelectorAll('[data-support-reply]').forEach(f=>f.onsubmit=guarded(async()=>{await result(db.from('support_requests').update({reply:f.querySelector('textarea').value.trim()}).eq('id',f.dataset.supportReply));toast('Reply saved.');}));$('#support-prev').onclick=()=>supportInbox(page-1).catch(fail);$('#support-next').onclick=()=>supportInbox(page+1).catch(fail);$('#support-home').onclick=()=>moderatorCenter().catch(fail);}
 return {deleteAccount,support,feedback,moderatorCenter};
}
