// Kitsu lookup is proxied through the website server, preserving anime/manga identity.
const cache=new Map();
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export async function searchCatalog(query,medium=null){const term=query.trim();const key=(medium||'both')+':'+term.toLowerCase();if(cache.has(key))return cache.get(key);const url=new URL('/api/catalog',location.origin);url.search=new URLSearchParams({q:term,...(medium?{medium}:{})});const response=await fetch(url,{signal:AbortSignal.timeout(35000)});const json=await response.json();if(!response.ok)throw Error(json.error||'Catalog search is temporarily unavailable.');const rows=(json.data||[]).sort((a,b)=>{const aExact=[a.title,a.english].some(t=>t?.toLowerCase()===term.toLowerCase()),bExact=[b.title,b.english].some(t=>t?.toLowerCase()===term.toLowerCase());return Number(bExact)-Number(aExact)||a.title.localeCompare(b.title)||a.medium.localeCompare(b.medium);});cache.set(key,rows);if(cache.size>100)cache.delete(cache.keys().next().value);return rows;}
export function attachCatalog(input,{getMedium,onSelect,onClear}){
 const holder=document.createElement('div');holder.className='catalog-picker';input.parentNode.insertBefore(holder,input);holder.append(input);const box=document.createElement('div');box.className='catalog-options';box.id=input.id+'-options';box.setAttribute('role','listbox');box.hidden=true;holder.append(box);input.setAttribute('role','combobox');input.setAttribute('aria-autocomplete','list');input.setAttribute('aria-controls',box.id);input.setAttribute('aria-expanded','false');input.autocomplete='off';let timer,generation=0,items=[],active=-1,selected=null;
 function position(){const r=holder.getBoundingClientRect(),below=innerHeight-r.bottom-100,above=r.top-90;const upward=below<180&&above>below;box.style.top=upward?'auto':'calc(100% + 5px)';box.style.bottom=upward?'calc(100% + 5px)':'auto';box.style.maxHeight=Math.max(100,Math.min(320,upward?above:below))+'px';}
 function hide(){box.hidden=true;input.setAttribute('aria-expanded','false');input.removeAttribute('aria-activedescendant');active=-1;}
 function select(item){generation++;clearTimeout(timer);selected=item;input.value=item.label;hide();onSelect(item);}
 function highlight(){const options=box.querySelectorAll('[role=option]');options.forEach((o,i)=>o.setAttribute('aria-selected',String(i===active)));if(active>=0){input.setAttribute('aria-activedescendant',options[active].id);options[active].scrollIntoView({block:'nearest'});}}
 async function run(){const request=++generation,term=selected&&input.value===selected.label?selected.title:input.value.trim();box.hidden=false;position();input.setAttribute('aria-expanded','true');box.innerHTML='<p role="status">Searching catalog…</p>';items=[];active=-1;try{const rows=await searchCatalog(term,getMedium());if(request!==generation||!input.isConnected)return;items=rows;box.innerHTML=rows.length?rows.map((r,i)=>`<button type="button" role="option" aria-selected="false" id="${box.id}-${i}" data-option="${i}"><strong>${escape(r.label)}</strong><span>${escape([r.format,r.year,r.english&&r.english!==r.title?r.english:null].filter(Boolean).join(' · '))}</span></button>`).join(''):'<p role="status">No matching series found.</p>';box.querySelectorAll('[data-option]').forEach(b=>{b.onmousedown=e=>e.preventDefault();b.onclick=()=>select(items[Number(b.dataset.option)]);});}catch(e){if(request!==generation)return;box.innerHTML=`<p role="status">${escape(e.message)} Type again to retry.</p>`;}}
 input.addEventListener('focus',()=>{clearTimeout(timer);run();});input.addEventListener('click',()=>{if(box.hidden){clearTimeout(timer);run();}});input.addEventListener('input',()=>{generation++;clearTimeout(timer);selected=null;onClear?.();hide();timer=setTimeout(run,450);});input.addEventListener('keydown',e=>{if(e.key==='Escape'){generation++;clearTimeout(timer);hide();return;}if(box.hidden)return;if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();if(!items.length)return;active=(active+(e.key==='ArrowDown'?1:-1)+items.length)%items.length;highlight();}if(e.key==='Enter'&&active>=0){e.preventDefault();select(items[active]);}});input.addEventListener('blur',()=>{setTimeout(()=>{if(!holder.contains(document.activeElement)){generation++;clearTimeout(timer);hide();}},150);});
 return {setSelection:select,reset(){generation++;clearTimeout(timer);input.value='';selected=null;hide();},close(){generation++;clearTimeout(timer);hide();}};
}


