const drafts=new WeakMap();
const reactions=[['hello','Hello','hi hey wave'],['laugh','Laugh','lol funny haha'],['wow','Wow','surprised amazing'],['yes','Yes','yay celebrate agree'],['thanks','Thanks','thank you grateful'],['love','Love it','heart love']];
const emojis=['😀','😄','😂','🥹','😊','😍','🥰','😎','🤔','😮','😭','😅','😴','🤯','😤','🥳','❤️','💚','🔥','✨','👏','🙌','👍','👎','🙏','💯','👀','🎉','🍿','⚔️','📚','🌸'];
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function safeGif(value){
 if(reactions.some(([id])=>value==='/reaction-'+id+'.gif'))return value;
 try{const u=new URL(value);if(u.protocol==='https:'&&!u.username&&!u.password&&!u.port&&['media.giphy.com','i.giphy.com','media.tenor.com'].includes(u.hostname)&&/\.gif$/i.test(u.pathname)&&u.href.length<=500)return u.href;}catch{}
 return null;
}
export function renderRichBody(body){return String(body||'').split(/(\[gif:[^\]\n]+\])/g).map(part=>{if(part.startsWith('[gif:')&&part.endsWith(']')){const url=safeGif(part.slice(5,-1));if(url)return `<img class="reply-gif" src="${escape(url)}" alt="GIF reaction" loading="lazy" referrerpolicy="no-referrer">`;}return escape(part);}).join('');}
export function composerBody(input){const gif=drafts.get(input)?.gif;const body=[input.value.trim(),gif?'[gif:'+gif+']':''].filter(Boolean).join('\n');if(body.length>input.maxLength)throw Error('Shorten your text before adding a GIF.');return body;}
export function clearComposer(input){const draft=drafts.get(input);input.value='';if(draft){draft.gif=null;draft.preview.replaceChildren();draft.panel.hidden=true;input.required=draft.required;input.closest('form').querySelectorAll('.reply-tools button').forEach(b=>b.setAttribute('aria-expanded','false'));}}
export function attachRichComposer(input){
 if(!input||drafts.has(input))return;const form=input.closest('form');if(!form)return;
 const toolbar=document.createElement('div');toolbar.className='reply-tools';toolbar.innerHTML='<button type="button" aria-label="Add emoji" title="Add emoji">☺</button><button type="button" aria-label="Add GIF" title="Add GIF">GIF</button>';
 const panel=document.createElement('section');panel.className='reply-picker';panel.hidden=true;panel.setAttribute('aria-label','Emoji and GIF picker');
 const preview=document.createElement('div');preview.className='reply-gif-preview';const draft={gif:null,panel,preview,required:input.required};drafts.set(input,draft);
 const submit=form.querySelector('button.primary,button[type="submit"]');form.insertBefore(toolbar,submit);const dock=document.createElement('div');dock.className='reply-picker-dock';dock.append(preview,panel);form.after(dock);const existing=input.value.match(/\[gif:([^\]\n]+)\]/);if(existing&&safeGif(existing[1])){input.value=input.value.replace(existing[0],'').trim();draft.gif=safeGif(existing[1]);input.required=false;preview.innerHTML=`<img src="${escape(draft.gif)}" alt="Selected GIF" referrerpolicy="no-referrer"><button type="button" aria-label="Remove GIF">×</button>`;preview.querySelector('button').onclick=()=>{draft.gif=null;preview.replaceChildren();input.required=draft.required;input.focus();};}
 let start=input.value.length,end=start;input.addEventListener('select',()=>{start=input.selectionStart;end=input.selectionEnd;});input.addEventListener('keyup',()=>{start=input.selectionStart;end=input.selectionEnd;});input.addEventListener('click',()=>{start=input.selectionStart;end=input.selectionEnd;});
 const close=()=>{panel.hidden=true;toolbar.querySelectorAll('button').forEach(b=>b.setAttribute('aria-expanded','false'));};
 function chooseGif(url){if((input.value.trim().length+url.length+7)>input.maxLength)return;draft.gif=url;input.required=false;preview.innerHTML=`<img src="${escape(url)}" alt="Selected GIF" referrerpolicy="no-referrer"><button type="button" aria-label="Remove GIF">×</button>`;preview.querySelector('button').onclick=()=>{draft.gif=null;preview.replaceChildren();input.required=draft.required;input.focus();};close();input.focus();}
 toolbar.querySelectorAll('button').forEach((button,index)=>{button.setAttribute('aria-expanded','false');button.onclick=()=>{input.focus();if(!panel.hidden&&panel.dataset.mode===String(index)){close();return;}panel.dataset.mode=String(index);panel.hidden=false;toolbar.querySelectorAll('button').forEach(b=>b.setAttribute('aria-expanded',String(b===button)));panel.innerHTML='<div class="reply-picker-heading"><strong>'+ (index?'GIFs':'Emojis')+'</strong><button type="button" aria-label="Close picker">×</button></div>';panel.querySelector('button').onclick=close;
 if(!index){const grid=document.createElement('div');grid.className='emoji-grid';emojis.forEach(emoji=>{const b=document.createElement('button');b.type='button';b.textContent=emoji;b.setAttribute('aria-label','Insert '+emoji);b.onclick=()=>{if(input.value.length-(end-start)+emoji.length>input.maxLength)return;input.setRangeText(emoji,start,end,'end');start=end=input.selectionStart;input.dispatchEvent(new Event('input',{bubbles:true}));input.focus();close();};grid.append(b);});panel.append(grid);}
 else{panel.insertAdjacentHTML('beforeend','<label>Search reactions<input class="gif-search" placeholder="Love, laugh, thanks…"></label><div class="gif-grid"></div><label>Or paste a GIF link<input class="gif-url" type="url" placeholder="https://media.giphy.com/…/giphy.gif"></label><p class="small">Use a direct .gif link from GIPHY or Tenor.</p><button type="button" class="gif-add">Attach GIF link</button><p class="gif-error" role="status"></p>');const grid=panel.querySelector('.gif-grid'),search=panel.querySelector('.gif-search');const paint=()=>{grid.replaceChildren();reactions.filter(r=>r.join(' ').toLowerCase().includes(search.value.toLowerCase())).forEach(([id,label])=>{const b=document.createElement('button');b.type='button';b.setAttribute('aria-label','Choose '+label+' GIF');b.innerHTML=`<img src="/reaction-${id}.gif" alt="${label}" loading="lazy">`;b.onclick=()=>chooseGif('/reaction-'+id+'.gif');grid.append(b);});};search.oninput=paint;paint();panel.querySelector('.gif-add').onclick=()=>{const url=safeGif(panel.querySelector('.gif-url').value.trim());if(!url){panel.querySelector('.gif-error').textContent='Paste a direct HTTPS .gif link from GIPHY or Tenor.';return;}chooseGif(url);};}
 };});panel.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();close();input.focus();}});
}
