import {createBillingServer} from './billing-server.mjs';
import {launchAccess} from './launch-access.mjs';
import http from 'node:http';
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
import {catalogResponse} from './catalog-server.mjs';
import {reviewRequest,reviewStatus} from './ai-review-server.mjs';
const port=Number(process.env.PORT||4173),hosts=process.env.HOST?[process.env.HOST]:['127.0.0.1','::1'];
const root=path.dirname(fileURLToPath(import.meta.url));
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.gif':'image/gif'};
const errorBudget=new Map();
const billingHandler=createBillingServer();
const handler=async(req,res)=>{try{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('X-Frame-Options','DENY');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');const url=new URL(req.url,'http://localhost');if(url.pathname==='/api/moderator/launch-checklist'){const r=await launchAccess(new Request(url,{method:req.method,headers:req.headers}));res.writeHead(r.status,Object.fromEntries(r.headers));res.end(await r.text());return;}if(await billingHandler(req,res,url))return;if(url.pathname==='/healthz'){res.writeHead(200,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify({ok:true}));return;}if(url.pathname==='/api/client-error'){if(req.method!=='POST'){res.writeHead(405);res.end();return;}const origin=req.headers.origin;if(origin&&origin!==new URL((req.headers['x-forwarded-proto']==='https'?'https':'http')+'://'+req.headers.host).origin){res.writeHead(403);res.end();return;}const ip=req.socket.remoteAddress,now=Date.now();if(now-(errorBudget.get(ip)||0)<60000){res.writeHead(429);res.end();return;}let chunks=[],size=0;for await(const chunk of req){size+=chunk.length;if(size>128){res.writeHead(413);res.end();return;}chunks.push(chunk);}const {code}=JSON.parse(Buffer.concat(chunks));if(!['runtime','async'].includes(code)){res.writeHead(400);res.end();return;}errorBudget.set(ip,now);if(errorBudget.size>1000)for(const [k,t] of errorBudget)if(now-t>60000)errorBudget.delete(k);console.warn(JSON.stringify({event:'client_error',code,at:new Date().toISOString()}));res.writeHead(204);res.end();return;}if(url.pathname==='/api/review/status'){res.writeHead(200,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(reviewStatus()));return;}if(url.pathname==='/api/review'){if(req.method!=='POST'){res.writeHead(405);res.end();return;}const reply=await reviewRequest(req);res.writeHead(reply.status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(reply.body));return;}if(url.pathname==='/api/catalog'){if(req.method!=='GET'){res.writeHead(405);res.end();return;}const reply=await catalogResponse(url);res.writeHead(reply.status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(reply.body));return;}const name=decodeURIComponent(url.pathname);const file=path.resolve(root,'.'+(name==='/'?'/index.html':name));if(!file.startsWith(root+path.sep)||!types[path.extname(file)]){res.writeHead(404);res.end('Not found');return;}const data=await readFile(file);res.writeHead(200,{'Content-Type':types[path.extname(file)],'Cache-Control':'no-store'});res.end(data);}catch{console.warn(JSON.stringify({event:'request_failed',at:new Date().toISOString()}));res.writeHead(404);res.end('Not found');}};for(const host of hosts)http.createServer(handler).listen(port,host,()=>console.log('FictionCom listening on '+host+':'+port));

