export function sharedBody(body,render){return render(body).replace(/\[share:([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})\]/gi,(_,id)=>`<button type="button" class="shared-content" data-shared-content="${id}"><span aria-hidden="true">↗</span> View shared post or story <span aria-hidden="true">›</span></button>`);}
export function createSharing({db,result,esc,requireProfile,uid,fail,toast,openPost,openStoryPost}){
 async function open(id){const post=await result(db.from('posts').select('*,profiles!posts_author_fkey(*)').eq('id',id).maybeSingle());if(!post||post.status!=='approved'||post.expires_at&&Date.parse(post.expires_at)<=Date.now()){toast('This post or story is no longer available.');return;}if(post.kind==='story')await openStoryPost(post);else await openPost(id);}
 async function share(id){if(!requireProfile())return;const pause=document.querySelector('#pause-story');if(pause&&pause.dataset.paused!=='true')pause.click();let dialog=document.querySelector('#share-dialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='share-dialog';dialog.className='share-dialog';document.body.append(dialog);}dialog.innerHTML='<div class="share-heading"><h2>Share to Chat</h2><button type="button" aria-label="Close sharing">×</button></div><label>Find a person<input id="share-search" autocomplete="off" placeholder="Search username…"></label><p class="small">People you follow appear first. Other people receive a message request. Private content can only be shared with people who can view it.</p><div id="share-people"></div>';dialog.querySelector('[aria-label="Close sharing"]').onclick=()=>dialog.close();dialog.showModal();const list=dialog.querySelector('#share-people'),input=dialog.querySelector('input');let epoch=0,timer;
 const draw=rows=>{list.innerHTML=rows.map(p=>`<button type="button" class="share-person" data-share-recipient="${p.id}"><span class="avatar">${esc(p.display_name?.[0]||'•')}</span><span><strong>${esc(p.display_name)}</strong><span class="meta">@${esc(p.username)}</span></span><span>Send ↗</span></button>`).join('')||'<p class="small">No people found. Search for a username.</p>';list.querySelectorAll('button').forEach(button=>button.onclick=async()=>{list.querySelectorAll('button').forEach(b=>b.disabled=true);try{const sent=await result(db.rpc('share_to_chat',{target_post:id,target_recipient:button.dataset.shareRecipient}));document.querySelectorAll('[data-share]').forEach(b=>{if(b.dataset.share===id)b.textContent='↗ '+sent.shares;});dialog.close();toast(sent.state==='pending'?'Shared as a message request.':'Shared to Chat.');}catch(e){fail(e);}finally{list.querySelectorAll('button').forEach(b=>b.disabled=false);}});};
 const follows=await result(db.from('follows').select('following').eq('follower',uid()).eq('accepted',true));if(!dialog.open)return;const ids=follows.map(f=>f.following);draw(ids.length?await result(db.from('profiles').select('id,username,display_name').in('id',ids).limit(25)):[]);
 input.oninput=()=>{clearTimeout(timer);const query=input.value.trim().replace(/[%_]/g,''),request=++epoch;if(query.length<2){list.innerHTML='<p class="small">Type at least two characters to search.</p>';return;}timer=setTimeout(async()=>{try{const rows=await result(db.from('profiles').select('id,username,display_name').ilike('username','%'+query+'%').neq('id',uid()).limit(25));if(request===epoch&&dialog.open)draw(rows);}catch(e){fail(e);}},250);};
 }
 return {share,open};
}
