import {validateMedia,configureCaptureButtons} from './media-validation.js';
// Photo edits are rendered into the uploaded image, not just its preview.
export function openStoryEditor({modal,onPublish,onClose}) {
 modal(`<h2>Create your story</h2><p class="small">Choose or capture a photo or a video up to 60 seconds.</p><input id="story-photo" type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" hidden><input id="story-camera-photo" type="file" accept="image/*" capture="environment" hidden><input id="story-camera-video" type="file" accept="video/*" capture="environment" hidden><div class="story-editor-layout"><div class="story-editor-preview"><canvas id="story-canvas" width="720" height="1280" aria-label="Story photo preview. Drag text to reposition it."></canvas><video id="story-video-preview" controls playsinline hidden></video><p id="story-placeholder">Choose a photo or video</p></div><div class="story-tools"><button id="choose-story-photo" class="quiet">Choose photo or video</button><div class="capture-actions"><button type="button" id="take-story-photo">Take photo</button><button type="button" id="take-story-video">Record video</button></div><p class="small">Videos: up to 60 seconds. Camera capture is available on supported devices. Up to 10 MB.</p><label>Picture filter<select id="story-filter"><option value="none">Original</option><option value="grayscale(1)">Black & white</option><option value="sepia(.45) saturate(1.2)">Warm</option><option value="saturate(1.4) contrast(1.12)">Vivid</option><option value="brightness(1.12) saturate(.8)">Soft</option><option value="sepia(.2) hue-rotate(170deg) saturate(.8)">Cool</option></select></label><button id="add-story-text">＋ Add text</button><label>Selected text<textarea id="story-text" maxlength="240" placeholder="Write something…" rows="2"></textarea></label><div class="story-text-options"><label>Text color<input id="story-color" type="color" value="#ffffff"></label><label>Text size<input id="story-size" type="range" min="24" max="80" value="44"></label></div><label class="check"><input id="story-text-bg" type="checkbox" checked> Text background</label><button id="remove-story-text" class="quiet">Remove selected text</button><p class="small">Drag text on the preview to move it.</p><details><summary>Spoiler label</summary><label>Series<input id="story-series" maxlength="100"></label><label>Format<select id="story-medium"><option value="anime">Anime</option><option value="manga">Manga</option></select></label><label>Episode / chapter<input id="story-episode" type="number" min="1" max="100000"></label><label class="check"><input id="story-spoiler" type="checkbox"> Contains spoilers</label></details><label class="check"><input id="story-rules" type="checkbox"> I confirm this photo follows the no-nudity and community rules.</label><p class="small">Stories last 24 hours. Do not upload nudity or inappropriate pictures.</p><p id="story-editor-error" class="error" role="alert"></p></div><div class="story-editor-footer"><button id="publish-story" class="primary" disabled>Post to story</button></div></div>`);
 const $=s=>document.querySelector(s);$('#modal').classList.add('story-editor-modal');const canvas=$('#story-canvas'),ctx=canvas.getContext('2d');
 let videoFile=null,videoUrl=null,photo=null,layers=[],selected=-1,drag=null,publishing=false,selectionVersion=0;
 const active=()=>layers[selected];
 function lines(text){const out=[];for(const para of text.split('\n')){let line='';for(const word of para.split(' ')){const next=line?line+' '+word:word;if(ctx.measureText(next).width>640&&line){out.push(line);line=word;}else line=next;}out.push(line);}return out;}
 function draw(){ctx.clearRect(0,0,720,1280);ctx.fillStyle='#101321';ctx.fillRect(0,0,720,1280);if(photo){const scale=Math.min(720/photo.width,1280/photo.height);ctx.save();ctx.filter=$('#story-filter').value;ctx.drawImage(photo,(720-photo.width*scale)/2,(1280-photo.height*scale)/2,photo.width*scale,photo.height*scale);ctx.restore();}
 for(const l of layers){if(!l.text.trim())continue;ctx.font=`700 ${l.size}px sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';const rows=lines(l.text),h=rows.length*l.size*1.25,w=Math.min(680,Math.max(...rows.map(t=>ctx.measureText(t).width))+28);l.box={x:l.x-w/2,y:l.y-h/2-8,w,h:h+16};if(l.background){ctx.fillStyle='#101321c9';ctx.fillRect(l.box.x,l.box.y,w,h+16);}ctx.fillStyle=l.color;rows.forEach((line,i)=>ctx.fillText(line,l.x,l.y+(i-(rows.length-1)/2)*l.size*1.25,652));}
 $('#publish-story').disabled=(!photo&&!videoFile)||!$('#story-rules').checked||publishing;
 }
 function select(index){selected=index;const l=active();$('#story-text').value=l?.text||'';$('#story-color').value=l?.color||'#ffffff';$('#story-size').value=l?.size||44;$('#story-text-bg').checked=l?.background??true;draw();}
 function add(){layers.push({text:'',x:360,y:640,color:'#ffffff',size:44,background:true});select(layers.length-1);$('#story-text').focus();}
 const input=$('#story-photo');async function choose(file){if(!file)return;const version=++selectionVersion;$('#story-editor-error').textContent='';try{await validateMedia(file,60);if(!canvas.isConnected||version!==selectionVersion)return;const bitmap=file.type.startsWith('image/')?await createImageBitmap(file,{imageOrientation:'from-image'}):null;if(!canvas.isConnected||version!==selectionVersion){bitmap?.close();return;}photo?.close();photo=bitmap;videoFile=bitmap?null:file;if(videoUrl)URL.revokeObjectURL(videoUrl);videoUrl=videoFile?URL.createObjectURL(file):null;const preview=$('#story-video-preview');preview.pause();preview.removeAttribute('src');preview.hidden=!videoFile;if(videoUrl)preview.src=videoUrl;canvas.hidden=!!videoFile;$('#story-placeholder').hidden=true;$('#choose-story-photo').textContent='Change photo or video';for(const id of ['story-filter','add-story-text','story-text','story-color','story-size','story-text-bg','remove-story-text'])$('#'+id).disabled=!!videoFile;draw();}catch(e){$('#story-editor-error').textContent=e.message;}}
 for(const id of ['story-photo','story-camera-photo','story-camera-video'])$('#'+id).onchange=e=>{const file=e.target.files[0];e.target.value='';choose(file)};
 const configureCapture=()=>configureCaptureButtons($('#take-story-photo'),$('#take-story-video'),$('#story-camera-photo'),$('#story-camera-video'));configureCapture();
 $('#take-story-photo').onclick=()=>$('#story-camera-photo').click();$('#take-story-video').onclick=()=>$('#story-camera-video').click();
 $('#choose-story-photo').onclick=()=>input.click();$('#add-story-text').onclick=add;$('#remove-story-text').onclick=()=>{if(selected>=0){layers.splice(selected,1);select(Math.min(selected,layers.length-1));}};
 for(const name of ['filter','rules'])$('#story-'+name).onchange=draw;
 $('#story-text').oninput=()=>{if(!active()){layers.push({text:'',x:360,y:640,color:'#ffffff',size:44,background:true});selected=layers.length-1;}active().text=$('#story-text').value;draw();};
 for(const [name,field] of [['color','color'],['size','size'],['text-bg','background']])$('#story-'+name).oninput=()=>{if(!active())return;active()[field]=name==='size'?Number($('#story-size').value):name==='text-bg'?$('#story-text-bg').checked:$('#story-color').value;draw();};
 const point=e=>{const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*720/r.width,y:(e.clientY-r.top)*1280/r.height};};
 canvas.onpointerdown=e=>{if(publishing)return;const p=point(e);for(let i=layers.length-1;i>=0;i--){const b=layers[i].box;if(b&&p.x>=b.x&&p.x<=b.x+b.w&&p.y>=b.y&&p.y<=b.y+b.h){select(i);drag={x:p.x-layers[i].x,y:p.y-layers[i].y};canvas.setPointerCapture(e.pointerId);break;}}};
 canvas.onpointermove=e=>{if(!drag||!active())return;const p=point(e);active().x=Math.max(40,Math.min(680,p.x-drag.x));active().y=Math.max(60,Math.min(1220,p.y-drag.y));draw();};canvas.onpointerup=canvas.onpointercancel=()=>{drag=null;};
 $('#publish-story').onclick=async()=>{if((!photo&&!videoFile)||publishing||!$('#story-rules').checked)return;const spoiler=$('#story-spoiler').checked,episode=Number($('#story-episode').value)||null;if(spoiler&&(!$('#story-series').value.trim()||!episode)){$('#story-editor-error').textContent='Add a series and episode/chapter for the spoiler label.';return;}publishing=true;draw();$('#publish-story').textContent='Posting…';const controls=[...$('.story-tools').querySelectorAll('input,select,textarea,button')];controls.forEach(c=>c.disabled=true);try{const metadata={kind:'story',title:'',body:'',series:$('#story-series').value.trim(),medium:$('#story-medium').value,episode,spoiler};if(videoFile){await onPublish(videoFile,metadata);return;}const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',.9));if(!blob)throw Error('Unable to prepare your photo. Try another image.');await onPublish(new File([blob],'story.jpg',{type:'image/jpeg'}),metadata);}catch(e){if($('#story-editor-error'))$('#story-editor-error').textContent=e.message||'Upload failed. Your edits are still here.';}finally{publishing=false;if(canvas.isConnected){controls.forEach(c=>c.disabled=false);configureCapture();$('#publish-story').textContent='Post to story';draw();}}};
 const cleanup=()=>{selectionVersion++;photo?.close();$('#story-video-preview')?.pause();if(videoUrl)URL.revokeObjectURL(videoUrl);};$('#modal').addEventListener('close',cleanup,{once:true});draw();
}
